/*
 * pci.c
 */
#include <sys/types.h>
#include <sys/seg.h>
#include <sys/errno.h>
#include <sys/immu.h>
#include <sys/param.h>
#include <sys/kmem.h>
#include <sys/eisa.h>
#include <sys/ipl.h>
#include <sys/pic.h>
#include <stdarg.h>

#include "pci.h"
#include "pci_ids.h"
#include "pci_funcs.h"

struct resource_region {
	u32_t	base;
	u32_t	size;
	u32_t	type;
	char	*name;	
	caddr_t	addr;
};

#define MAX_RR	128
struct resource_region _RR[MAX_RR];

extern int pci_debug;
extern int level_intr_mask;

int	elcr_status;
int	elcr_found=0;
u8_t	pci_remaps[4] = { 0 };
u8_t 	Pbn, Pdevfn;
pci_router_ops_t	*pci_router = 0;

static pci_router_ops_t pci_generic_router_ops =
{
	"PCI",
	PCI_route,
	0x60,
	PCI_ROUTER_PRI_GENERIC
};

static void
pci_set_router(pci_router_ops_t *router)
{
	if (router == 0)
		return;

	if (pci_router == 0 || router->priority > pci_router->priority) {
		DrvDebug(_PCI,5,
			"PCI router: %s selected (replacing %s)\n",
			router->name,
			pci_router ? pci_router->name : "(none)");
		pci_router = router;
	} else {
		DrvDebug(_PCI,5,
			"PCI router: keeping %s, ignoring %s\n",
			pci_router->name, router->name);
	}
}

i440fx_t	i440;
piix3_t		piix3;
piix4_t		piix4;
via_t		via;

pcibus_t 	pci_root;
pcidev_t 	*pci_devices = 0;

/* Programmable Interrupt Controllers */

/* defined in conf.c, which is generated by config: */
extern  int     (*ivect[])();           /* interrupt routines */
extern  unsigned char intpri[];         /* priority levels for interrupts */
extern  int     nintr;                  /* number of interrupts */

extern  unsigned short imrport[];       /* intr mask port addrs for pics */
extern  unsigned char masterline[];     /* line this pic connected to */
extern  unsigned char curmask[];        /* current masks for pics */
extern  int     npic;                   /* number of pics configured */
extern 	int picmax;               /* index of last pic */

/*
 * iplmask[] contains the pic masks for each interrupt priority level.
 * It is effectively dimensioned iplmask[IPLHI][NPIC],
 * and is initialized from intpri[].
 * IPLHI=8 NPIC=2
 */
extern  unsigned char iplmask[];

extern  int     intnull();              /* null interrupt routine */
extern	int	splvalid_flag;

extern int ipl;                  /* current interrupt priority level */
extern int picipl;               /* interrupt priority level of pic masks */

int	PCI_route(int,int,...);

/*
 * Main SVR4 Driver Entry points
 */
void
pciinit()
{
	uint_t	tmp;
	int	x;
	extern int verbose_bios;

	DrvDebug(_PCI,5,"pciinit()\n");
	if (pci_debug>0)
		verbose_bios=1;

	if (pci_devices != 0) return;

	bzero(_RR,sizeof(_RR));

	outl(CFG_ADDR,0);
	tmp=inl(CFG_ADDR);
	if (tmp != 0x00000000)
	{
		printf("No PCI devices found\n");
		return;
	}

		pci_set_router(&pci_generic_router_ops);
	scan_bios();

	bzero(&pci_root, sizeof(pci_root));
	pci_root.subordinate = scan_bus(&pci_root);

	if (elcr_probe() != 0)
		printf("PCI: ELCR not found, level-triggered IRQs not available\n");

	/* Register the chipset driver */
	(void)I440FX_init();
	(void)PIIX3_init();
	(void)PIIX4_init();
	(void)VIA_init();

	/*show_pirq();
	show_irqroute();*/
	return; 
}

int
pciopen()
{
	DrvDebug(_PCI,5,"pciopen()\n");
	
	return 0;
}

int
pciclose()
{
	DrvDebug(_PCI,5,"pciclose()\n");

	return 0;
}

int
pciread()
{
	DrvDebug(_PCI,5,"pciread()\n");

	return 0;
}
		
int
pci(int mode,u8_t bus,u8_t devfn,u8_t reg,u32_t value,int sz)
{
	u32_t	addr;
	u32_t	val;
	int	n;

	if (sz != 1 && sz != 2 && sz != 4) return -1;

	n=((int)reg%sizeof(u32_t))<<3;
	reg &= ~(sizeof(u32_t)-1);
			
	addr = PCI_ADDR(bus,devfn)|reg;
	outl(CFG_ADDR,addr);

	switch(mode) {
	case PCI_RD:
		if (value == 0) return -1;
		val=inl(CFG_DATA);
		switch(sz) {
		case 1:
			*(u8_t *)(ptrsize_t)value=(u8_t)((val>>n)&0xff);
			break;
		case 2:
			*(u16_t *)(ptrsize_t)value=(u16_t)((val>>n)&0xffff);
			break;
		case 4:
			*(u32_t *)(ptrsize_t)value=val;
			break;
		}
		break;

	case PCI_WR:
		val=inl(CFG_DATA);
		switch(sz) {
		case 1:
			val &= ~(0x000000ffU<<n);
			val |= (value & 0x000000ffU)<<n;
			break;
		case 2:
			val &= ~(0x0000ffffU<<n);
			val |= (value & 0x0000ffffU)<<n;
			break;
		case 4:
			val = value;
			break;
		}
		outl(CFG_ADDR,addr);
		outl(CFG_DATA,val);
		break;
	default:
		return -1;
	}
	return 0;
}

int
pci_ffs(int mask)
{
	int 	bit;

	if (mask==0) return 0;
	for(bit=1;!(mask&1); bit++)
		mask=(uint_t)mask>>1;
	return bit;
}

char 
IntPin(u8_t pin)
{
	switch(pin)
	{
	case 0: return '-';
	case 1: return 'A';
	case 2: return 'B';
	case 3: return 'C';
	case 4: return 'D';
	default: return '?';
	}
}


u32_t
barsize(u32_t mask)
{
	if (mask == 0) 
		return 0;
	return mask & (~mask + 1);
}

void
burst_bridge(u8_t bus, u8_t devfn, u8_t pos, int turn_on)
{
	DrvDebug(_PCI,5,"burst_bridge()\n");
}

void *
pci_malloc(int size)
{
	void	*mem=kmem_zalloc(size,KM_NOSLEEP);
	return mem;
}

int
get_num_bars(u8_t hdrtype)
{
	switch(hdrtype & 0x7f) {
	case 0: return 6;
	case 1: return 2;
	case 2: return 1;
	}
	return 0;
}

u32_t
get_map_base(u32_t addr) 
{
	if  (addr & 0x01)
		return addr & ~0x03;
	else
		return addr & ~0x0f;
}

static void
pci_print_one_device(pcidev_t *dev)
{
	int	i;
	u8_t	base, sub, prog;
	char	*vendor_name;
	char	*device_name;
	char	*class_name;
	char	*subclass_name;

	DrvDebug(_PCI,5,"pci_print_one_device()\n");

	base = (u8_t)((dev->class >> 16) & 0xff);
	sub  = (u8_t)((dev->class >> 8) & 0xff);
	prog = (u8_t)(dev->class & 0xff);

	vendor_name = get_pci_vendor_name(dev->vendor);
	device_name = get_pci_dev(dev->vendor, dev->device);
	class_name = get_pci_class_name(base);
	subclass_name = get_pci_subclass_name(base, sub);

	printf("PCI: %02x:%02x.%x ",
		dev->bn,
		PCI_SLOT(dev->devfn),
		PCI_FUNC(dev->devfn));

	if (device_name != 0)
		printf("%s", device_name);
	else if (subclass_name != 0)
		printf("%s", subclass_name);
	else if (class_name != 0)
		printf("%s", class_name);
	else
		printf("Unknown PCI Device");

	printf(" [%04x:%04x]", dev->vendor, dev->device);
	if (vendor_name != 0)
		printf(" (%s)", vendor_name);
	printf(" class=%02x/%02x/%02x", base, sub, prog);
	if (dev->intpin != 0 || dev->irq != PCI_INVALID_IRQ)
		printf(" IRQ:%d INT#%c", dev->irq, IntPin(dev->intpin));
	printf("\n");

	for (i = 0; i < DEVICE_COUNT_RESOURCE; i++) {
		if (dev->resource[i].flags == 0)
			continue;

		printf("  BAR%d ", i);
		if (dev->resource[i].flags & IORESOURCE_IO)
			printf("IO  %08lx-%08lx",
				(unsigned long)dev->resource[i].start,
				(unsigned long)dev->resource[i].end);
		else if (dev->resource[i].flags & IORESOURCE_MEM)
			printf("MEM %08lx-%08lx",
				(unsigned long)dev->resource[i].start,
				(unsigned long)dev->resource[i].end);
		else
			printf("??? %08lx-%08lx",
				(unsigned long)dev->resource[i].start,
				(unsigned long)dev->resource[i].end);

		printf("\n");
	}
}

void
pci_print_devices(void)
{
	pcidev_t *dev;

	DrvDebug(_PCI,5,"pci_print_devices()\n");

	if (pci_devices == 0) {
		printf("PCI: no devices enumerated\n");
		return;
	}

	printf("PCI: enumerated devices\n");
	for (dev = pci_devices; dev != 0; dev = dev->next)
		pci_print_one_device(dev);
	printf("\n");
}

u32_t
scan_bus(pcibus_t *bus)
{
	pcidev_t	*dev;
	pcibus_t	*child;
	u32_t		l, iostart, iosize, buses;
	u16_t		cmd, tmp, vid, did, ssvid, ssdid, cr;
	u32_t		class;
	u8_t		bn, max, hdr, mf, rev;
	u8_t		master, irq, intpin;
	u8_t		devfn;
	int		i, slot, fn, num_bars, nfuncs;
	resource_t	res[DEVICE_COUNT_RESOURCE];

	DrvDebug(_PCI,5,"scan_bus()\n");

	max = bus->secondary;
	bn  = bus->number;

	for (slot = 0; slot < 32; slot++)
	{
		hdr = vid = did = 0;
		devfn = DEVFN(slot, 0);

		prcw(bn, devfn, PCI_VENDOR_ID, &vid);
		if (vid == 0xffff || vid == 0x0000)
			continue;

		/* Read header type from function 0 to determine
		 * whether this is a multi-function device. */
		prcb(bn, devfn, PCI_HEADER_TYPE, &hdr);
		if (hdr == 0xff)
			continue;		/* slot not populated */

		mf    = (hdr & 0x80) ? 1 : 0;
		hdr  &= ~0x80;
		nfuncs = mf ? 8 : 1;

		for (fn = 0; fn < nfuncs; fn++)
		{
			devfn = DEVFN(slot, fn);

			/* For fn > 0 re-read vendor to skip unpopulated
			 * functions in a multi-function device. */
			if (fn > 0) {
				vid = 0;
				prcw(bn, devfn, PCI_VENDOR_ID, &vid);
				if (vid == 0xffff || vid == 0x0000)
					continue;
			}

			prcw(bn, devfn, PCI_DEVICE_ID, &did);
			if (did == 0xffff)
				continue;

			/* Re-read header type for each function it can
			 * differ across functions of the same device. */
			if (fn > 0) {
				hdr = 0;
				prcb(bn, devfn, PCI_HEADER_TYPE, &hdr);
				if (hdr == 0xff)
					continue;
				hdr &= ~0x80;
			}

			num_bars = get_num_bars(hdr);

			/* Subsystem vendor is at 0x2c, subsystem ID at 0x2e.
			 * These registers are only valid for header type 0. */
			ssvid = 0;
			ssdid = 0;
			if ((hdr & 0x7f) == 0) {
				prcw(bn, devfn, PCI_SUBSYSTEM_VENDOR_ID, &ssvid);
				prcw(bn, devfn, PCI_SUBSYSTEM_ID,        &ssdid);
			}

			/* Class (24 bits) and revision (8 bits) share one
			 * DWORD at offset 0x08. */
			l   = 0;
			prcd(bn, devfn, PCI_CLASS_REVISION, &l);
			rev   = (u8_t)(l & 0xff);
			class = (l >> 8) & 0x00ffffffU;

			/* BAR probing: size each BAR with decode disabled and always
			 * restore the original contents before leaving the probe path.
			 * Also consume the upper dword of 64-bit memory BARs so later
			 * BARs are not mis-parsed. */
			bzero(res, sizeof(res));
			for (i = 0; i < num_bars; i++)
			{
				u32_t bar_reg = PCI_BASE_ADDRESS_0 + (i * 4);
				u32_t size;
				u32_t orig_bar, probe_bar;
				u32_t orig_bar_hi, probe_bar_hi;
				u16_t probe_cmd, restore_cmd;
				int wrote_probe, wrote_probe_hi, is64;

				iosize = 0;
				orig_bar = 0;
				probe_bar = 0;
				orig_bar_hi = 0;
				probe_bar_hi = 0;
				probe_cmd = 0;
				restore_cmd = 0;
				wrote_probe = 0;
				wrote_probe_hi = 0;
				is64 = 0;
				res[i].start = 0;
				res[i].end   = 0;
				res[i].flags = 0;

				if (prcd(bn, devfn, bar_reg, &orig_bar) != 0)
					continue;

				iostart = orig_bar;
				if (iostart == 0 || iostart == 0xffffffff)
					continue;

				if (!(iostart & PCI_BASE_ADDRESS_SPACE_IO) &&
				    ((iostart & PCI_BASE_ADDRESS_MEM_TYPE_MASK) ==
				     PCI_BASE_ADDRESS_MEM_TYPE_64)) {
					is64 = 1;
					if ((i + 1) >= num_bars)
						continue;
					if (prcd(bn, devfn, bar_reg + 4, &orig_bar_hi) != 0)
						continue;
					if (orig_bar_hi != 0)
						printf("PCI: %02x:%02x.%x BAR%d 64-bit base truncated to 32 bits\n",
							bn, PCI_SLOT(devfn), PCI_FUNC(devfn), i);
					res[i + 1].start = 0;
					res[i + 1].end   = 0;
					res[i + 1].flags = 0;
				}

				if (prcw(bn, devfn, PCI_COMMAND, &probe_cmd) != 0)
					continue;
				restore_cmd = probe_cmd;
				probe_cmd &= ~(PCI_COMMAND_IO | PCI_COMMAND_MEMORY);
				if (pwcw(bn, devfn, PCI_COMMAND, probe_cmd) != 0)
					continue;

				if (pwcd(bn, devfn, bar_reg, 0xffffffffU) == 0) {
					wrote_probe = 1;
					if (prcd(bn, devfn, bar_reg, &probe_bar) == 0)
						iosize = probe_bar;
					if (is64 && pwcd(bn, devfn, bar_reg + 4, 0xffffffffU) == 0) {
						wrote_probe_hi = 1;
						(void)prcd(bn, devfn, bar_reg + 4, &probe_bar_hi);
					}
				}

				if (wrote_probe_hi)
					(void)pwcd(bn, devfn, bar_reg + 4, orig_bar_hi);
				if (wrote_probe)
					(void)pwcd(bn, devfn, bar_reg, orig_bar);
				(void)pwcw(bn, devfn, PCI_COMMAND, restore_cmd);

				if (!wrote_probe || iosize == 0 || iosize == 0xffffffff)
					continue;
				if (is64 && probe_bar_hi != 0 && probe_bar_hi != 0xffffffff)
					printf("PCI: %02x:%02x.%x BAR%d 64-bit size truncated to 32 bits\n",
						bn, PCI_SLOT(devfn), PCI_FUNC(devfn), i);

				res[i].start = get_map_base(iostart);
				if (iostart & PCI_BASE_ADDRESS_SPACE_IO) {
					size = barsize(iosize & PCI_BASE_ADDRESS_IO_MASK);
					res[i].flags = IORESOURCE_IO;
				} else {
					size = barsize(iosize & PCI_BASE_ADDRESS_MEM_MASK);
					res[i].flags = IORESOURCE_MEM;
				}
				res[i].end = size ? (res[i].start + size - 1) : 0;

				if (is64)
					i++;
			}

			/* Non-destructively test whether device supports
			 * bus mastering. */
			master = 0;
			if ((prcw(bn, devfn, PCI_COMMAND, &cmd) == 0) &&
			    (pwcw(bn, devfn, PCI_COMMAND, (cmd | PCI_COMMAND_MASTER)) == 0) &&
			    (prcw(bn, devfn, PCI_COMMAND, &tmp) == 0))
			{
				master = ((tmp & PCI_COMMAND_MASTER) != 0) ? 1 : 0;
				pwcw(bn, devfn, PCI_COMMAND, cmd);
			}

			/* Read IRQ line and interrupt pin.*/
			irq    = 0;
			intpin = 0;
			if (prcb(bn, devfn, PCI_INTERRUPT_LINE, &irq) != 0) continue;
			if (prcb(bn, devfn, PCI_INTERRUPT_PIN,  &intpin) != 0) continue;
			if (intpin > 4) intpin=0;

			/* Allocate device and info structures.
			 * Bug fixed: original allocated dev then immediately
			 * tested dev->info in the same if-condition, but if
			 * dev allocation succeeded and info allocation failed
			 * the already-allocated dev was leaked. Fix: allocate
			 * and test separately. */
			dev = pci_malloc(sizeof(pcidev_t));
			if (dev == 0)
				continue;

			dev->info = pci_malloc(sizeof(pcidevinfo_t));
			if (dev->info == 0) {
				kmem_free(dev, sizeof(pcidev_t));
				continue;
			}

			dev->bus              = bus;
			dev->bn               = bus->number;
			dev->devfn            = devfn;
			dev->vendor           = vid;
			dev->device           = did;
			dev->subsystem_vendor = ssvid;
			dev->subsystem_device = ssdid;
			dev->revision         = rev;
			dev->class            = class;
			dev->hdr_type         = hdr;
			dev->master           = master;
			dev->irq              = irq;
			dev->intpin           = intpin;
			bcopy(&res, &dev->resource, sizeof(res));

			dev->info->vendor = vid;
			dev->info->device = did;
			dev->info->name   = "Unknown PCI Device";

			/* Prepend to global device list and bus device list. */
			dev->next    = pci_devices;
			pci_devices  = dev;
			dev->sibling = bus->devices;
			bus->devices = dev;

			/* If this is a PCI-to-PCI bridge, allocate a child
			 * bus structure, assign tentative bus numbers, recurse
			 * to scan subordinate buses, then write the final
			 * subordinate number back. */
			if (dev->class == PCI_CLASS_BRIDGE_PCI)
			{
				child = kmem_zalloc(sizeof(pcibus_t), KM_NOSLEEP);
				if (child == 0)
					continue;

				child->self        = dev;
				child->parent      = bus;
				child->number      = ++max;
				child->secondary   = max;
				child->primary     = bus->number;
				child->subordinate = 0xff;

				child->next  = bus->children;
				bus->children = child;

				/* Disable the bridge while we configure it and always
				 * restore the original command register on exit. */
				if (prcw(bn, devfn, PCI_COMMAND, &cr) == 0) {
					u32_t orig_buses = 0;
					int bridge_cfg_ok = 1;

					if (pwcw(bn, devfn, PCI_COMMAND, 0x0000) != 0)
						bridge_cfg_ok = 0;
					if (bridge_cfg_ok && pwcw(bn, devfn, PCI_STATUS, 0xffff) != 0)
						bridge_cfg_ok = 0;
					if (bridge_cfg_ok && prcd(bn, devfn, 0x18, &orig_buses) != 0)
						bridge_cfg_ok = 0;

					buses = orig_buses;
					if (bridge_cfg_ok) {
						buses &= 0xff000000U;
						buses |= ((u32_t)child->primary     <<  0)
						       | ((u32_t)child->secondary   <<  8)
						       | ((u32_t)child->subordinate << 16);
						if (pwcd(bn, devfn, 0x18, buses) != 0)
							bridge_cfg_ok = 0;
					}

					if (bridge_cfg_ok) {
						/* Recurse — fills in child->subordinate. */
						max = scan_bus(child);

						/* Write the real subordinate number back. */
						child->subordinate = max;
						buses = (buses & 0xff00ffffU)
						      | ((u32_t)max << 16);
						if (pwcd(bn, devfn, 0x18, buses) != 0) {
							bridge_cfg_ok = 0;
							(void)pwcd(bn, devfn, 0x18, orig_buses);
						}
					}

					/* Re-enable the bridge. */
					(void)pwcw(bn, devfn, PCI_COMMAND, cr);
					if (!bridge_cfg_ok)
						printf("PCI: %02x:%02x.%x bridge configuration incomplete\n",
							bn, PCI_SLOT(devfn), PCI_FUNC(devfn));
				}
			}
		}
	}
	return max;
}

static pcidevid_t *
pci_match_one_device(pcidev_t *dev,pcidevid_t *id)
{
	if ((id->vendor == PCI_ANY_ID || id->vendor == dev->vendor) &&
	    (id->device == PCI_ANY_ID || id->device == dev->device) &&
	    (id->subvendor == PCI_ANY_ID || 
	     id->subvendor == dev->subsystem_vendor) &&
	    (id->subdevice == PCI_ANY_ID || 
	     id->subdevice == dev->subsystem_device) &&
	    !((id->class ^ dev->class) & id->class_mask))
		return id;
	return 0;
}

pcidev_t *
find_pcidev(u8_t bus,u8_t devfn)
{
	pcidev_t *dev;

	DrvDebug(_PCI,5,"find_pcidev()\n");

	/*** For each pci_devices */
	for(dev=pci_devices; dev; dev=dev->next)
	{
		/* printf("dev %02x.%02x.%x [%04x,%04x]\n",
			dev->bn,dev->devfn,
			dev->vendor,dev->device);*/
		if (dev->bn == bus &&
		    dev->devfn == devfn)
			return dev; 
	}
	return (pcidev_t *)0;
}

/*
 * called with (struct pci_driver *)&pcnet_driver
 */
int
pci_register_driver(struct pci_driver *drv)
{
	pcidev_t *dev;
	pcidevid_t *id;
	int	count=0;

	DrvDebug(_PCI,5,"pci_register_driver(%s)\n",drv ? drv->name : "??");

	if (!drv || !drv->id_table)
		return -EINVAL;

	/*** For each pci_devices */
	for(dev=pci_devices; dev; dev=dev->next)
	{
		/*
		printf("dev %x %02x.%02x.%x [%04x,%04x]\n",
			dev,
			dev->bn,PCI_SLOT(dev->devfn),PCI_FUNC(dev->devfn),
			dev->vendor,dev->device); */

		for(id=drv->id_table; id->vendor; id++)
		{
			if (pci_match_one_device(dev,id) != 0) {
				int ret=0;

				if (drv->probe)
					ret = (*drv->probe)(dev,id);

				if (ret == 0) {
					dev->info->name=drv->name;
					count++;
					break;
				}
			}
		}
	}
	return count;
}

uint_t	pcibios_max_latency = 255;

int
pci_is_enabled(pcidev_t *dev)
{
	return dev->enable_cnt > 0;
}

void
pci_set_master(pcidev_t *dev)
{
	u16_t	cmd;
	u8_t	lat=0;

	DrvDebug(_PCI,5,"pci_set_master()\n");

	if (dev == 0)
		return;

	if (prcw(dev->bn, dev->devfn, PCI_COMMAND, &cmd) != 0)
		return;

	if (!(cmd & PCI_COMMAND_MASTER)) {
		cmd |= PCI_COMMAND_MASTER;
		if (pwcw(dev->bn, dev->devfn, PCI_COMMAND, cmd) != 0)
			return;
	}

	dev->is_busmaster = 1;

	if (prcb(dev->bn,dev->devfn,PCI_LATENCY_TIMER,&lat) == 0) {
		if (lat < 16) {
			lat=64;	
			pwcb(dev->bn,dev->devfn,PCI_LATENCY_TIMER,lat);
		}
	}
	return;
}

pcidev_t *
pci_physfn(pcidev_t *dev)
{
	/* if (dev->is_virtfn)
		dev=dev->physfn;*/
	return dev;
}

pcidev_t *
pci_upstream_bridge(pcidev_t *dev)
{
	dev=pci_physfn(dev);
	if (pci_is_root_bus(dev->bus))
		return NULL;
	return dev->bus->self;
}

void
pci_enable_bridge(pcidev_t *dev)
{
	pcidev_t *bridge;
	int	retval;

	DrvDebug(_PCI,5,"pci_enable_bridge()\n");

	bridge=pci_upstream_bridge(dev);
	if (bridge)
		pci_enable_bridge(bridge);
	if (pci_is_enabled(dev)) {
		if (!dev->is_busmaster)
			pci_set_master(dev);
		return;
	}
	retval=pci_device_enable(dev);
	if (retval)
		printf("Error enabling device %02d:%02d.%d\n",
			dev->bn,
			PCI_SLOT(dev->devfn),
			PCI_FUNC(dev->devfn));
	pci_set_master(dev);
}

int
pci_is_root_bus(pcibus_t *bus)
{
	return !(bus->parent);
}

int
pci_is_bridge(pcidev_t *dev)
{
	return dev->hdr_type == PCI_HEADER_TYPE_BRIDGE ||
	       dev->hdr_type == PCI_HEADER_TYPE_CARDBUS;
}

int
do_pci_device_enable(pcidev_t *dev,int bars)
{
	u16_t	cmd, newcmd;
	int	i;

	DrvDebug(_PCI,5,"do_pci_device_enable()\n");

	if (dev == 0)
		return -EINVAL;

	if (prcw(dev->bn, dev->devfn, PCI_COMMAND, &cmd) != 0)
		return -EIO;

	newcmd = cmd;

	for (i = 0; i < PCI_ROM_RESOURCE; i++) {
		if (!(bars & (1 << i)))
			continue;
		if (dev->resource[i].flags & IORESOURCE_IO)
			newcmd |= PCI_COMMAND_IO;
		if (dev->resource[i].flags & IORESOURCE_MEM)
			newcmd |= PCI_COMMAND_MEMORY;
	}
	for (i = PCI_BRIDGE_RESOURCES; i < DEVICE_COUNT_RESOURCE; i++) {
		if (!(bars & (1 << i)))
			continue;
		if (dev->resource[i].flags & IORESOURCE_IO)
			newcmd |= PCI_COMMAND_IO;
		if (dev->resource[i].flags & IORESOURCE_MEM)
			newcmd |= PCI_COMMAND_MEMORY;
	}

	/* Preserve historical behaviour: if the device probed as bus-master
	 * capable, enable mastering as part of device enable. */
	if (dev->master)
		newcmd |= PCI_COMMAND_MASTER;

	if (newcmd == cmd) {
		if (newcmd & PCI_COMMAND_MASTER)
			dev->is_busmaster = 1;
		return 0;
	}

	if (pwcw(dev->bn, dev->devfn, PCI_COMMAND, newcmd) != 0)
		return -EIO;

	if (newcmd & PCI_COMMAND_MASTER)
		dev->is_busmaster = 1;

	return 0;
}

int
pci_device_disable(pcidev_t *dev)
{
	u16_t	cmd;

	DrvDebug(_PCI,5,"pci_device_disable()\n");

	if (dev == 0)
		return -EINVAL;

	if (dev->enable_cnt <= 0) {
		dev->enable_cnt = 0;
		return 0;
	}

	dev->enable_cnt--;
	if (dev->enable_cnt > 0)
		return 0;

	if (prcw(dev->bn, dev->devfn, PCI_COMMAND, &cmd) != 0)
		return -EIO;

	cmd &= ~(PCI_COMMAND_IO | PCI_COMMAND_MEMORY | PCI_COMMAND_MASTER);

	if (pwcw(dev->bn, dev->devfn, PCI_COMMAND, cmd) != 0)
		return -EIO;

	dev->is_busmaster = 0;
	return 0;
}

int
pci_device_enable_flags(pcidev_t *dev,u32_t flags)
{
	pcidev_t *bridge;
	int	err, i, bars=0;

	DrvDebug(_PCI,5,"pci_device_enable_flags()\n");

	if (dev->pm_cap) {
		u16_t 	pmcsr;

		if (prcw(dev->bus->number,
			      dev->devfn,
			      dev->pm_cap+PCI_PM_CTRL,
			      &pmcsr) == 0)
			dev->current_state=(pmcsr&PCI_PM_CTRL_STATE_MASK);
	}
	if (dev->enable_cnt > 0) {
		dev->enable_cnt++;
		return 0;
	}

	dev->enable_cnt++;
	bridge=pci_upstream_bridge(dev);
	if (bridge)
		pci_enable_bridge(bridge);

	for (i=0;i<PCI_ROM_RESOURCE;i++)
		if (dev->resource[i].flags & flags)
			bars |= (1<<i);
	for (i=PCI_BRIDGE_RESOURCES;i<DEVICE_COUNT_RESOURCE;i++)
		if (dev->resource[i].flags & flags)
			bars |= (1<<i);
	err=do_pci_device_enable(dev,bars);
	if (err<0)
		dev->enable_cnt=0;
	return err;
}

int
pci_device_enable(pcidev_t *dev)
{
	return pci_device_enable_flags(dev,IORESOURCE_MEM|IORESOURCE_IO);
}

int
pci_set_dma_mask(pcidev_t *dev,u32_t mask)
{
	dev->dma_mask = mask;
	return 0;
}

static int
rr_overlap(u32_t base1, u32_t size1, u32_t base2, u32_t size2)
{
	u32_t end1, end2;

	if (size1 == 0 || size2 == 0)
		return 0;

	end1 = base1 + size1;
	end2 = base2 + size2;

	if (end1 <= base1 || end2 <= base2)
		return 0;

	return (base1 < end2 && end1 > base2);
}

int
request_region(u32_t type, u32_t base, u32_t size, char *name)
{
	int	i, free_slot;
	caddr_t	addr;
	u32_t	end;

	DrvDebug(_PCI,5,"request_region(%d,%x,%x,%s)\n",
		type, base, size, name ? name : "(null)");

	if (type != RES_MEM && type != RES_IO)
		return 0;

	if (size == 0)
		return 0;

	end = base + size;
	if (end <= base)
		return 0;

	free_slot = -1;

	for (i = 0; i < MAX_RR; i++) {
		if (_RR[i].size == 0) {
			if (free_slot < 0)
				free_slot = i;
			continue;
		}

		if (_RR[i].type != type)
			continue;

		if (rr_overlap(base, size, _RR[i].base, _RR[i].size)) {
			DrvDebug(_PCI,5,
			    "request_region: overlap [%x..%x) with [%x..%x) %s\n",
			    base, base + size,
			    _RR[i].base, _RR[i].base + _RR[i].size,
			    _RR[i].name ? _RR[i].name : "(unnamed)");
			return 0;
		}
	}

	if (free_slot < 0) {
		printf("MAX Resources RR reached for PCI\n");
		return 0;
	}

	addr = 0;
	if (type == RES_MEM) {
		addr = (caddr_t)physmap(base, size, KM_NOSLEEP);
		if (addr == 0)
			return 0;
	}

	_RR[free_slot].base = base;
	_RR[free_slot].size = size;
	_RR[free_slot].type = type;
	_RR[free_slot].name = name;
	_RR[free_slot].addr = addr;

	return 1;
}

int
release_region(u32_t type, u32_t base, u32_t size)
{
	int	i;

	DrvDebug(_PCI,5,"release_region(%d,%x,%x)\n", type, base, size);

	for (i = 0; i < MAX_RR; i++) {
		if (_RR[i].size == 0)
			continue;

		if (_RR[i].type != type)
			continue;

		if (_RR[i].base == base && _RR[i].size == size) {
			if (type == RES_MEM && _RR[i].addr != 0)
				physmap_free(_RR[i].addr, _RR[i].size, KM_NOSLEEP);

			_RR[i].base = 0;
			_RR[i].size = 0;
			_RR[i].type = RES_NONE;
			_RR[i].name = 0;
			_RR[i].addr = 0;
			return 1;
		}
	}

	return 0;
}

int
request_mem_region(u32_t base, u32_t size, char *name)
{
	return request_region(RES_MEM, base, size, name);
}

int
release_mem_region(u32_t base, u32_t size)
{
	return release_region(RES_MEM, base, size);
}

int
request_io_region(u32_t base, u32_t size, char *name)
{
	return request_region(RES_IO, base, size, name);
}

int
release_io_region(u32_t base, u32_t size)
{
	return release_region(RES_IO, base, size);
}

/*
 * pic_add_handler() - update PIC masks after adding a new IRQ handler
 * must be called at spl7() with interrupts disabled
 */
void
pic_add_handler()
{
	int 	mask,intno, bit, slaves, level, pic;

	DrvDebug(_PCI,9,"pic_add_handler()\n");

	/*
	 * if picinit() has not yet run skip the hw update
	 * picinit() will pick this up when it runs
	 */
	if (!splvalid_flag)
		return;

	for (pic=0; pic<npic; pic++) {
		mask=0;
		intno = pic * 8;
		for(bit=1; bit<=0x80; bit<<=1, intno++) {
			if (intno >= nintr || ivect[intno] == intnull) {
				mask |= bit;
				for(level=SPLTTY; level<IPLHI; level++)
					iplmask[level * npic+pic] |= bit;
			} else {
				level = intpri[intno];
				for(; level<IPLHI; level++)
					iplmask[level * npic+pic] |= bit;
			}
		}
		iplmask[pic]=mask;
	}

	/* Re-enable slave cascade lines on master */
	slaves = 0;	
	for(pic=1; pic<npic; pic++)
		slaves |= 1 << masterline[pic];
	iplmask[0] &= ~slaves;

	/* Write new OCW1 masks only - no ICW sequence */
	for(pic=0; pic<npic; pic++)
		outb(imrport[pic], (curmask[pic] = iplmask[pic]));
}

int I440FX_init();
int I440FX_probe_pci(pcidev_t *, pcidevid_t *);
int I440FX_route(int cmd,int,...);
int PIIX4_init();
int PIIX4_probe_pci(pcidev_t *, pcidevid_t *);
int PIIX4_route(int,int,...);
int PIIX3_init();
int PIIX3_probe_pci(pcidev_t *, pcidevid_t *);
int PIIX3_route(int,int,...);
int VIA_init();
int VIA_probe_pci(pcidev_t *, pcidevid_t *);
int VIA_route(int,int,...);

static pcidevid_t I440FX_pci_tbl[] = 
{
    { PCI_DEVICE(PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_82441) },
    { 0, }
};

struct pci_driver I440FX_driver = 
{
	"I440FX",
	I440FX_probe_pci,
	0,
	I440FX_pci_tbl,
	0
};

static pci_router_ops_t i440fx_router_ops =
{
	"I440FX",
	I440FX_route,
	0x60,
	PCI_ROUTER_PRI_440FX
};

int 
I440FX_init()
{
	int	I440FX_have_pci=0;

	if (pci_devices == 0)
		pciinit();

	if (pci_register_driver(&I440FX_driver))
		I440FX_have_pci=1;
	else
		DrvDebug(_PCI,5,"I440FX_init(): Not Found\n");

	return (I440FX_have_pci) ? 0 : -ENODEV;
}

int
I440FX_probe_pci(pcidev_t *pdev, pcidevid_t *ent)
{
	int	err=0, i, pin;

	DrvDebug(_PCI,5,"I440FX_probe_pci(%02d:%02d.%d)\n",
		pdev->bn,PCI_SLOT(pdev->devfn),PCI_FUNC(pdev->devfn));

	err=pci_device_enable(pdev);
	if (err < 0) {
		printf("Failed to enable device\n");
		return err;
	}
	pci_set_master(pdev);
	/*** pci_set_router(&i440fx_router_ops); ***/ /*NO*/

	prcw(pdev->bn,pdev->devfn,PCI_VENDOR_ID,&i440.f0.vid);
	prcw(pdev->bn,pdev->devfn,PCI_DEVICE_ID,&i440.f0.did);
	prcw(pdev->bn,pdev->devfn,PCI_COMMAND,&i440.f0.pcicmd);
	prcw(pdev->bn,pdev->devfn,PCI_STATUS,&i440.f0.pcists);
	prcb(pdev->bn,pdev->devfn,0x0d,&i440.f0.mlt);
	prcb(pdev->bn,pdev->devfn,PCI_HEADER_TYPE,&i440.f0.hdr);
	prcb(pdev->bn,pdev->devfn,0x0f,&i440.f0.bist);
	prcb(pdev->bn,pdev->devfn,0x3c,&i440.f0.intln);
	prcb(pdev->bn,pdev->devfn,0x3d,&i440.f0.intpn);
	prcw(pdev->bn,pdev->devfn,0x50,&i440.f0.pmccfg);
	prcb(pdev->bn,pdev->devfn,0x52,&i440.f0.deturbo);
	prcb(pdev->bn,pdev->devfn,0x53,&i440.f0.dbc);
	prcb(pdev->bn,pdev->devfn,0x54,&i440.f0.axc);
	prcw(pdev->bn,pdev->devfn,0x55,&i440.f0.dramr);
	prcb(pdev->bn,pdev->devfn,0x57,&i440.f0.dramc);
	prcb(pdev->bn,pdev->devfn,0x58,&i440.f0.dramt);
	for(i=0;i<7;i++)
		prcb(pdev->bn,pdev->devfn,0x59+i,&i440.f0.pam[i]);
	for(i=0;i<8;i++)
		prcb(pdev->bn,pdev->devfn,0x60+i,&i440.f0.drb[i]);
	prcb(pdev->bn,pdev->devfn,0x68,&i440.f0.fdhc);
	prcb(pdev->bn,pdev->devfn,0x70,&i440.f0.mtt);
	prcb(pdev->bn,pdev->devfn,0x71,&i440.f0.clt);
	prcb(pdev->bn,pdev->devfn,0x72,&i440.f0.smram);
	prcb(pdev->bn,pdev->devfn,0x90,&i440.f0.errcmd);
	prcb(pdev->bn,pdev->devfn,0x91,&i440.f0.errsts);
	prcb(pdev->bn,pdev->devfn,0x93,&i440.f0.trc);
	for(pin=0;pin<DEVPCI_LEGACY_IRQ_PINS;pin++) 
				i440.f0.pirqrc[pin]=pci_router->route(PIRQ_GET,pin+1);
	if (pci_debug > 9) 
		I440FX_dump(pdev, ent);
	return 0;
}

int
I440FX_dump(pcidev_t *pdev, pcidevid_t *ent)
{
	printf("\nVID=[%x] DID=[%x] COMMAND=[%x] STATUS=[%x] HDR=[%x]\n",
			i440.f0.vid,i440.f0.did,i440.f0.pcicmd,
			i440.f0.pcists,i440.f0.hdr);
	printf("INTLN=[%d] INTPIN=[%d] MLT=[%x] BIST=[%x]\n",
		i440.f0.intln, i440.f0.intpn, i440.f0.mlt,i440.f0.bist);
	printf("PM=[%x] DETURBO=[%x] DBC=[%x] AXC=[%x]\n",
			i440.f0.pmccfg,i440.f0.deturbo,i440.f0.dbc,i440.f0.axc);
	printf("DRAMR=[%x] DRAMC=[%x] DRAMT=[%x]\n",
				i440.f0.dramr,i440.f0.dramc,i440.f0.dramt);
	printf("PAM0=[%x] PAM1=[%x] PAM2=%x PAM3=%x PAM4=%x PAM5=[%x]\n",
		i440.f0.pam[0],i440.f0.pam[1],i440.f0.pam[2],
		i440.f0.pam[3],i440.f0.pam[4],i440.f0.pam[5]);
	printf("DRB0=[%x] DRB1=[%x] DRB2=[%x] DRB3=[%x]\n",
		i440.f0.drb[0],i440.f0.drb[1],i440.f0.drb[2],i440.f0.drb[3]);
	printf("DRB4=[%x] DRB5=[%x] DRB6=[%x] DRB7=[%x]\n",
		i440.f0.drb[4],i440.f0.drb[5],i440.f0.drb[6],i440.f0.drb[7]);
	printf("FDHC=[%x] MTT=[%x] CLT=[%x] SMRAM=[%x]\n",
			i440.f0.fdhc,i440.f0.mtt,i440.f0.clt,i440.f0.smram);
	printf("ERRCMD=[%x] ERRSTS=[%x] TRC=[%x]\n",
				i440.f0.errcmd,i440.f0.errsts,i440.f0.trc);
	return 0;
}

int 
I440FX_route(int cmd,int pirq,...)
{
	va_list	ap;
	u8_t	irq=0;

	DrvDebug(_PCI,5,"I440FX_route(cmd=%d, pirq=%d): unsupported, routing handled by southbridge\n",
			cmd,pirq);
	return -ENODEV;
}

static pcidevid_t PIIX4_pci_tbl[] = 
{
    { PCI_DEVICE(PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_82371AB_0) },
    { 0, }
};

struct pci_driver PIIX4_driver = 
{
	"PIIX4",
	PIIX4_probe_pci,
	0,
	PIIX4_pci_tbl,
	0,
};

static pci_router_ops_t piix4_router_ops =
{
	"PIIX4",
	PIIX4_route,
	0x60,
	PCI_ROUTER_PRI_PIIX4
};


int 
PIIX4_init()
{
	int	PIIX4_have_pci=0;

	if (pci_devices == 0)
		pciinit();

	if (pci_register_driver(&PIIX4_driver))
		PIIX4_have_pci=1;
	else
		DrvDebug(_PCI,5,"PIIX4_init(): Not Found\n");

	return (PIIX4_have_pci) ? 0 : -ENODEV;
}

int
PIIX4_probe_pci(pcidev_t *pdev, pcidevid_t *ent)
{
	int	err=0, pin;

	DrvDebug(_PCI,5,"PIIX4_probe_pci(%02d:%02d.%d)\n",
		pdev->bn,PCI_SLOT(pdev->devfn),PCI_FUNC(pdev->devfn));

	err=pci_device_enable(pdev);
	if (err < 0) {
		printf("Failed to enable device\n");
		return err;
	}
	pci_set_master(pdev);
		pci_set_router(&piix4_router_ops);

	prcw(pdev->bn,pdev->devfn,PCI_VENDOR_ID,&piix4.f0.vid);
	prcw(pdev->bn,pdev->devfn,PCI_DEVICE_ID,&piix4.f0.did);
	prcw(pdev->bn,pdev->devfn,PCI_COMMAND,&piix4.f0.pcicmd);
	prcw(pdev->bn,pdev->devfn,PCI_STATUS,&piix4.f0.pcists);
	prcb(pdev->bn,pdev->devfn,PCI_HEADER_TYPE,&piix4.f0.hdr);
	prcb(pdev->bn,pdev->devfn,0x3c,&piix4.f0.intln);
	prcb(pdev->bn,pdev->devfn,0x3d,&piix4.f0.intpn);
	prcd(pdev->bn,pdev->devfn,0x40,&piix4.f0.pmba);
	prcd(pdev->bn,pdev->devfn,0x44,&piix4.f0.cnta);
	prcd(pdev->bn,pdev->devfn,0x48,&piix4.f0.cntb);
	prcd(pdev->bn,pdev->devfn,0x4c,&piix4.f0.gpictl);
	prcd(pdev->bn,pdev->devfn,0x54,&piix4.f0.devacta);
	prcd(pdev->bn,pdev->devfn,0x58,&piix4.f0.devactb);
	prcd(pdev->bn,pdev->devfn,0x5c,&piix4.f0.devresa);
	prcd(pdev->bn,pdev->devfn,0x60,&piix4.f0.devresb);

	/*** Pick up PIRQ settings ***/
	for(pin=0;pin<DEVPCI_LEGACY_IRQ_PINS;pin++) 
				piix4.f0.pirqrc[pin]=pci_router->route(PIRQ_GET,pin+1);

	prcd(pdev->bn,pdev->devfn,0x64,&piix4.f0.devresc);
	prcd(pdev->bn,pdev->devfn,0x50,&piix4.f0.devresd);
	prcd(pdev->bn,pdev->devfn,0x68,&piix4.f0.devrese);
	prcd(pdev->bn,pdev->devfn,0x6c,&piix4.f0.devresf);
	prcd(pdev->bn,pdev->devfn,0x70,&piix4.f0.devresg);
	prcd(pdev->bn,pdev->devfn,0x74,&piix4.f0.devresh);
	prcd(pdev->bn,pdev->devfn,0x78,&piix4.f0.devresi);
	prcd(pdev->bn,pdev->devfn,0x7c,&piix4.f0.devresj);
	prcd(pdev->bn,pdev->devfn,0x80,&piix4.f0.pmregmisc);
	prcd(pdev->bn,pdev->devfn,0x90,&piix4.f0.smbba);
	prcb(pdev->bn,pdev->devfn,0xd2,&piix4.f0.smbhstcfg);
	prcb(pdev->bn,pdev->devfn,0xd3,&piix4.f0.smbslvc);
	prcb(pdev->bn,pdev->devfn,0xd4,&piix4.f0.smbshdw1);
	prcb(pdev->bn,pdev->devfn,0xd5,&piix4.f0.smbshdw2);
	prcb(pdev->bn,pdev->devfn,0xd6,&piix4.f0.smbrev);
	prcd(pdev->bn,pdev->devfn,0x60,&pci_remaps);

	if (pci_debug>9)
		PIIX4_debug(pdev, ent);
	return 0;
}

int
PIIX4_debug(pcidev_t *pdev, pcidevid_t *ent)
{
	printf("\nVID=[%x] DID=[%x] COMMAND=[%x] STATUS=[%x] HDR=[%x]\n",
		piix4.f0.vid,piix4.f0.did,piix4.f0.pcicmd,
		piix4.f0.pcists,piix4.f0.hdr);
	printf("INTLN=[%d] INTPIN=[%d] PMBA=[%x]\n",
		piix4.f0.intln, piix4.f0.intpn, piix4.f0.pmba);
	printf("CNTA=[%x] CNTB=[%x] GPICTL=[%x]\n",
		piix4.f0.cnta, piix4.f0.cntb, piix4.f0.gpictl);
	printf("DEVACTA=[%x] DEVACTB=[%x] DEVRESA=[%x] DEVRESB=[%x]\n",
		piix4.f0.devacta, piix4.f0.devactb, 
		piix4.f0.devresa, piix4.f0.devresb);
	printf("DEVRESC=[%x] DEVRESD=[%x] DEVRESE=[%x] DEVRESF=[%x]\n",
		piix4.f0.devresc, piix4.f0.devresd, 
		piix4.f0.devrese, piix4.f0.devresf);
	printf("DEVRESG=[%x] DEVRESH=[%x] DEVRESI=[%x] DEVRESJ=[%x]\n",
		piix4.f0.devresg, piix4.f0.devresh, 
		piix4.f0.devresi, piix4.f0.devresj);
	printf("PMREGMISC=[%x] SMBBA=[%x]\n",piix4.f0.pmregmisc,piix4.f0.smbba);
	printf("SMBHSTCFG=[%x] SMBSLVC=[%x] SMBSHDW1=[%x] SMBSHDW2=[%x]\n",
		piix4.f0.smbhstcfg, piix4.f0.smbslvc, 
		piix4.f0.smbshdw1, piix4.f0.smbshdw2);
	printf("SMBREV=[%x]\n",piix4.f0.smbrev);
	printf("PIRQRC0=[%x] PIRQRC1=[%x] PIRQRC2=[%x] PIRQRC3=[%x]\n",
	      	piix4.f0.pirqrc[0],piix4.f0.pirqrc[1],
		piix4.f0.pirqrc[2],piix4.f0.pirqrc[3]);
	return 0;
}

int 
PIIX4_route(int cmd,int pirq,...)
{
	va_list	ap;
	u8_t	irq; 
	int	i;

	switch(cmd) {
	case PIRQ_GET:
		prcb(Pbn,Pdevfn,pci_router->pirq_base+pirq-1,&irq);
		DrvDebug(_PCI,5,"PIIX4_route(GET, PIRQ%c) -> %d\n",
			'A'+pirq-1,irq);
		return (int)irq;

	case PIRQ_SET:
		va_start(ap,pirq);	
		i=va_arg(ap,int);	
		va_end(ap);
		irq=(u8_t)i&0xff;
		pwcb(Pbn,Pdevfn,pci_router->pirq_base+pirq-1,irq);
		DrvDebug(_PCI,5,"PIIX4_route(SET, PIRQ%c -> IRQ %d)\n",
			'A'+pirq-1,irq);
		return 0;
	default:
		printf("Unknown cmd %d\n",cmd);
	}
	return -1;
}

static pcidevid_t PIIX3_pci_tbl[] = 
{
    { PCI_DEVICE(PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_82371SB_0) },
    { 0, }
};

struct pci_driver PIIX3_driver = 
{
	"PIIX3",
	PIIX3_probe_pci,
	0,
	PIIX3_pci_tbl,
	0
};

static pci_router_ops_t piix3_router_ops =
{
	"PIIX3",
	PIIX3_route,
	0x60,
	PCI_ROUTER_PRI_PIIX3
};

int 
PIIX3_init()
{
	int	PIIX3_have_pci=0;

	if (pci_devices == 0)
		pciinit();

	if (pci_register_driver(&PIIX3_driver))
		PIIX3_have_pci=1;
	else
		DrvDebug(_PCI,5,"PIIX3_init(): Not Found\n");

	return (PIIX3_have_pci) ? 0 : -ENODEV;
}

int
PIIX3_probe_pci(pcidev_t *pdev, pcidevid_t *ent)
{
	int	err=0, pin, i;

	DrvDebug(_PCI,5,"PIIX3_probe_pci(%02d:%02d.%d)\n",
		pdev->bn,PCI_SLOT(pdev->devfn),PCI_FUNC(pdev->devfn));

	err=pci_device_enable(pdev);
	if (err < 0) {
		printf("Failed to enable device\n");
		return err;
	}
		pci_set_router(&piix3_router_ops);

	prcw(pdev->bn,pdev->devfn,PCI_VENDOR_ID,&piix3.f0.vid);
	prcw(pdev->bn,pdev->devfn,PCI_DEVICE_ID,&piix3.f0.did);
	prcw(pdev->bn,pdev->devfn,PCI_COMMAND,&piix3.f0.pcicmd);
	prcw(pdev->bn,pdev->devfn,PCI_STATUS,&piix3.f0.pcists);
	prcb(pdev->bn,pdev->devfn,PCI_HEADER_TYPE,&piix3.f0.hdr);
	prcb(pdev->bn,pdev->devfn,0x3c,&piix3.f0.intln);
	prcb(pdev->bn,pdev->devfn,0x3d,&piix3.f0.intpn);
	prcb(pdev->bn,pdev->devfn,0x4c,&piix3.f0.iort);
	prcw(pdev->bn,pdev->devfn,0x4e,&piix3.f0.xbcs);

	/*** Pick up PIRQ settings ***/
	for(pin=0;pin<DEVPCI_LEGACY_IRQ_PINS;pin++) 
		piix3.f0.pirqrc[pin]=pci_router->route(PIRQ_GET,pin+1);

	prcb(pdev->bn,pdev->devfn,0x69,&piix3.f0.tom);
	prcw(pdev->bn,pdev->devfn,0x6b,&piix3.f0.mstat);
	for(i=0;i<2;i++)
		prcb(pdev->bn,pdev->devfn,0x70+i,&piix3.f0.mbirq[i]);
	for(i=0;i<2;i++)
		prcb(pdev->bn,pdev->devfn,0x76+i,&piix3.f0.mbdma[i]);
	prcw(pdev->bn,pdev->devfn,0x78,&piix3.f0.pcsc);
	prcb(pdev->bn,pdev->devfn,0x80,&piix3.f0.apicbase);
	prcb(pdev->bn,pdev->devfn,0x82,&piix3.f0.dlc);
	prcb(pdev->bn,pdev->devfn,0xa0,&piix3.f0.smicntl);
	prcw(pdev->bn,pdev->devfn,0xa2,&piix3.f0.smien);
	prcd(pdev->bn,pdev->devfn,0xa4,&piix3.f0.see);
	prcb(pdev->bn,pdev->devfn,0xa8,&piix3.f0.ftmr);
	prcw(pdev->bn,pdev->devfn,0xaa,&piix3.f0.smireq);
	prcb(pdev->bn,pdev->devfn,0xac,&piix3.f0.ctltmr);
	prcb(pdev->bn,pdev->devfn,0xae,&piix3.f0.cthtmr);
	prcd(pdev->bn,pdev->devfn,0x60,&pci_remaps);

	if (pci_debug > 9)
		PIIX3_debug(pdev, ent);
	return 0;
}

int
PIIX3_debug(pcidev_t *pdev, pcidevid_t *ent)
{
	printf("\nVID=[%x] DID=[%x] COMMAND=[%x] STATUS=[%x] HDR=[%x]\n",
		piix3.f0.vid, piix3.f0.did, piix3.f0.pcicmd,
		piix3.f0.pcists, piix3.f0.hdr);
	printf("INTLN=[%d] INTPIN=[%d] IORT=[%x] XBCS=[%x]\n",
		piix3.f0.intln, piix3.f0.intpn,piix3.f0.iort, piix3.f0.xbcs);
	printf("PIRQRCA=[%d] PIRQRCB=[%d] PIRQRCC=[%d] PIRWQCD=[%d]\n",
		piix3.f0.pirqrc[0], piix3.f0.pirqrc[1],
		piix3.f0.pirqrc[2], piix3.f0.pirqrc[3]);
	printf("TOM=[%x] MSTAT=[%x] MBIRQ0=[%x] MBIRQ1=[%x] MBDMA0=[%x]\n",
		piix3.f0.tom, piix3.f0.mstat, 
		piix3.f0.mbirq[0], piix3.f0.mbirq[1], piix3.f0.mbdma[0]);
	printf("MBDMA1=[%x] PCSC=[%x] APICBASE=[%x] DLC=[%x]\n",
		piix3.f0.mbdma[1],piix3.f0.pcsc,piix3.f0.apicbase,piix3.f0.dlc);
	printf("SMICNTL=[%x] SMIEN=[%x] SEE=[%x]\n",
		piix3.f0.smicntl, piix3.f0.smien, piix3.f0.see);
	printf("FTMR=[%x] SMIREQ=[%x] CTLTMR=[%x] CTHTMR=[%x]\n",
		piix3.f0.ftmr,piix3.f0.smireq,
		piix3.f0.ctltmr,piix3.f0.cthtmr);
	return 0;
}

int 
PIIX3_route(int cmd,int pirq,...)
{
	va_list	ap;
	u8_t	irq=0;
	int	i;

	switch(cmd) {
	case PIRQ_GET:
		prcb(Pbn,Pdevfn,pci_router->pirq_base+pirq-1,&irq);
		DrvDebug(_PCI,5,"PIIX3_route(GET, PIRQ%c) -> %d\n",
			'A'+pirq-1,irq);
		return (int)irq;

	case PIRQ_SET:
		va_start(ap,pirq);	
		i=va_arg(ap,int);	
		va_end(ap);
		irq=(u8_t)i&0xff;
		pwcb(Pbn,Pdevfn,pci_router->pirq_base+pirq-1,irq);
		DrvDebug(_PCI,5,"PIIX3_route(SET, PIRQ%c -> IRQ %d)\n",
			'A'+pirq-1,irq);
		return 0;
	default:
		printf("Unknown cmd %d\n",cmd);
	}
	return -1;
}

static pcidevid_t VIA_pci_tbl[] = 
{
    { PCI_DEVICE(PCI_VENDOR_ID_VIA, PCI_DEVICE_ID_VIA_82C686) },
    { 0, }
};

struct pci_driver VIA_driver = 
{
	"VIA",
	VIA_probe_pci,
	0,
	VIA_pci_tbl,
	0
};

static pci_router_ops_t via_router_ops =
{
	"VIA",
	VIA_route,
	0x55,
	PCI_ROUTER_PRI_VIA
};

int 
VIA_init()
{
	int	VIA_have_pci=0;

	if (pci_devices == 0) {
		pciinit();
	}

	if (pci_register_driver(&VIA_driver))
		VIA_have_pci=1;
	else
		DrvDebug(_PCI,5,"VIA_init(): Not Found\n");

	return (VIA_have_pci) ? 0 : -ENODEV;
}

int
VIA_probe_pci(pcidev_t *pdev, pcidevid_t *ent)
{
	int	err=0, pin;
	u16_t irq1,irq2;

	DrvDebug(_PCI,5,"VIA_probe_pci(%02d:%02d.%d)\n",
		pdev->bn,PCI_SLOT(pdev->devfn),PCI_FUNC(pdev->devfn));

	err=pci_device_enable(pdev);
	if (err < 0) {
		printf("Failed to enable device\n");
		return err;
	}
	pci_set_master(pdev);
		pci_set_router(&via_router_ops);

	prcw(pdev->bn,pdev->devfn,PCI_VENDOR_ID,&via.f0.vid);
	prcw(pdev->bn,pdev->devfn,PCI_DEVICE_ID,&via.f0.did);
	prcw(pdev->bn,pdev->devfn,PCI_COMMAND,&via.f0.pcicmd);
	prcw(pdev->bn,pdev->devfn,PCI_STATUS,&via.f0.pcists);
	prcb(pdev->bn,pdev->devfn,PCI_HEADER_TYPE,&via.f0.hdr);
	prcb(pdev->bn,pdev->devfn,PCI_CLASS_REVISION,&via.f0.revid);
	prcb(pdev->bn,pdev->devfn,0x3c,&via.f0.intln);
	prcb(pdev->bn,pdev->devfn,0x3d,&via.f0.intpn);

	prcb(pdev->bn,pdev->devfn,0x40,&via.f0.isabuscontrol);
	prcb(pdev->bn,pdev->devfn,0x46,&via.f0.misccontrol1);
	prcb(pdev->bn,pdev->devfn,0x47,&via.f0.misccontrol2);
	prcb(pdev->bn,pdev->devfn,0x48,&via.f0.misccontrol3);
	prcb(pdev->bn,pdev->devfn,0x4a,&via.f0.ideirqroute);
	prcb(pdev->bn,pdev->devfn,0x54,&via.f0.pciedgelevel);
	prcb(pdev->bn,pdev->devfn,0x55,&via.f0.pciinta);
	prcb(pdev->bn,pdev->devfn,0x56,&via.f0.pciintbc);
	prcb(pdev->bn,pdev->devfn,0x57,&via.f0.pciintd);
	prcb(pdev->bn,pdev->devfn,0x58,&via.f0.apicirq);
	prcb(pdev->bn,pdev->devfn,0x85,&via.f0.extfunc);

	/*** Pick up PIRQ settings ***/
	for(pin=0;pin<DEVPCI_LEGACY_IRQ_PINS;pin++) 
		via.f0.pirqrc[pin]=pci_router->route(PIRQ_GET,pin+1);

	prcw(Pbn,Pdevfn,0x44,&irq1);
	prcw(Pbn,Pdevfn,0x46,&irq2);
	/*printf("irq1=%x irq2=%x\n",irq1,irq2);*/
	prcd(pdev->bn,pdev->devfn,0x60,&pci_remaps);

	if (pci_debug > 9)
		VIA_dump(pdev, ent);

	return 0;
}

int
VIA_dump(pcidev_t *pdev, pcidevid_t *ent)
{
	int	i;

	printf("%02x %s\n",
		via.f0.revid,
		via.f0.revid&0x0f==1?"VT82C686A":"VT82C686");

	printf("\nVID=[%x] DID=[%x] COMMAND=[%x] STATUS=[%x] HDR=[%x]\n",
		via.f0.vid, via.f0.did, via.f0.pcicmd,
		via.f0.pcists, piix3.f0.hdr);
	printf("INTLINE=[%d] INTPIN=[%d]\n",
		via.f0.intln, via.f0.intpn);
	printf("MISC1=%08x MISC2=%08x MISC3=%08x\n",
		via.f0.misccontrol1,via.f0.misccontrol2,via.f0.misccontrol3);
	printf("IDEIRQROUTE=%08x PCIEDGELVL=%08x\n",
		via.f0.ideirqroute, via.f0.pciedgelevel);
	printf("PCIINTA=%08x PCIINTBC=%08x PCIINTD=%08x\n",
		via.f0.pciinta,via.f0.pciintbc,via.f0.pciintd);
	printf("APICIRQ=%08x EXTFUNC=%08x\n",
		via.f0.apicirq, via.f0.extfunc);

	printf("ISABUSCTRL=[%x] PCIEDGELEVEL=[%x] APICIRQ=[%x]\n",
		via.f0.isabuscontrol, 
		via.f0.pciedgelevel,
		via.f0.apicirq);
	printf("INTA=[%x] INTB=[%x] INTC=[%x] INTD=[%x]\n",
		via.f0.pciinta,
		LoNibble(via.f0.pciintbc),
		HiNibble(via.f0.pciintbc),
		via.f0.pciintd);

	for(i=0;i<4;i++)
	{
		if (via.f0.pciedgelevel & (1<<i))
			printf("PIRQ%c Edge\n",'A'+i);
		else
			printf("PIRQ%c Level\n",'A'+i);
	}
	printf("\n");
	return 0;
}

int 
VIA_route(int cmd,int pirq,...)
{
	va_list	ap;
	u8_t	val, irq;
	u8_t	reg;
	int	i;
	int	pirq_idx;

	if (pirq < 1 || pirq > 4) {
		DrvDebug(_PCI,5,"VIA_route: invalid PIRQ %d\n",pirq);
		return -1;
	}

	pirq_idx = pirq-1;
	reg = 0x55 + (pirq_idx / 2);

	switch(cmd) {
	case PIRQ_GET:
		prcb(Pbn, Pdevfn, reg, &val);

		if ((pirq_idx & 1) == 0)
			irq = val & 0x0f;
		else
			irq = (val >> 4) & 0x0f;

		DrvDebug(_PCI,5,"VIA_route(GET, PIRQ%c) -> IRQ %d (reg 0x%x= 0x%x)\n",
			'A'+pirq_idx,irq,reg,val);
		return (int)irq;

	case PIRQ_SET:
		va_start(ap,pirq);
		i=va_arg(ap,int);
		va_end(ap);	

		irq = (u8_t)i & 0x0f;

		prcb(Pbn, Pdevfn, reg, &val);

		if ((pirq_idx & 1) == 0)
			val = (val & 0xf0) | irq;
		else
			val = (val & 0x0f) | (irq << 4);
	
		pwcb(Pbn,Pdevfn, reg, val);

		DrvDebug(_PCI,5,"VIA_route(SET, PIRQ%c -> IRQ %d) (reg 0x%x = 0x%x)\n",
			'A' + pirq_idx,irq,reg,val);
		return 0;
	default:
		printf("Unknown cmd %d\n",cmd);
	}
	return -1;
}

int 
PCI_route(int cmd,int pirq,...)
{
	u8_t	irq=0; 
	va_list ap;
	int	i, r;

	pirq--;
	r = ((pci_router != 0) ? pci_router->pirq_base : 0x60) + pirq;

	switch(cmd) {
	case PIRQ_GET:
		prcb(Pbn,Pdevfn,r,&irq);
		irq &= 0x0f;
		DrvDebug(_PCI,5,"PCI_route(GET, PIRQ%c) -> %d\n",
			'A'+pirq,irq);
		return (int)irq;

	case PIRQ_SET:
		va_start(ap,pirq);
		i=va_arg(ap,int);
		va_end(ap);
		prcb(Pbn,Pdevfn,r,&irq);
		irq = (u8_t)(i & 0x0f);
		pwcb(Pbn,Pdevfn,r,irq);
		DrvDebug(_PCI,5,"PCI_route(SET, PIRQ%c -> IRQ %d)\n",
			'A'+pirq,irq);
		return 0;
	default:
		printf("Unknown cmd %d\n",cmd);
	}
	return -1;
}


int
pci_slot_get_pirq(u8_t devfn, int irq_num)
{
	int	slot_addend;

	slot_addend = (devfn >> 3) - 1;
	return (irq_num+slot_addend) & 3;
}

int
pci_slot_get_apic_pirq(u8_t devfn, int irq_num)
{
	return (irq_num + (devfn>>3)) & 7;
}

int
PCI_get_interrupt(pcidev_t *pdev)
{
	int	pirq;

	DrvDebug(_PCI,5,"PCI_get_interrupt(IRQ=%d, INT#%c)\n",pdev->irq,
						     IntPin(pdev->intpin));

	if (pdev->intpin == 0 || pdev->intpin > 4) {
		printf("PCI device does not specify interrupt pin\n");
		return pdev->irq;
	}	

	pirq = ((int)(PCI_INTX_TO_PIR(pdev->intpin) + PCI_SLOT(pdev->devfn)) % 4) ;

	DrvDebug(_PCI,5,"devfn=%04x [%c,irq=%d] pirq=%d maps to IRQ%d\n", 
		pdev->devfn,
		IntPin(pdev->intpin),
		pdev->irq,
		pirq,
		pci_remaps[pirq]);

	if (pci_remaps[pirq] == 0x00) {
		return pdev->irq;
	} else
	if (pci_remaps[pirq] >= 0x80) {
		printf("pci_get_intr(): Not mapped - remapping\n");

		if (pdev->irq == 0xff) {
			return PCI_INVALID_IRQ;
		}
		return pdev->irq;	
	}
	return pci_remaps[pirq];
}

void
show_irqroute()
{
	int	pin;

	printf("PCI interrupt router at: %02X:%02X.%X\n",
		Pbn,PCI_SLOT(Pdevfn),PCI_FUNC(Pdevfn));

	for(pin=0;pin<DEVPCI_LEGACY_IRQ_PINS;pin++)
	{
		u8_t irq;

		irq=pci_router->route(PIRQ_GET,pin+1);
		if (irq & 0x80)
			printf("PIRQ%c disabled\n",IntPin(PIR_TO_PCI_INTX(pin)));
		else
			printf("PIRQ%c -> IRQ%d\n",IntPin(PIR_TO_PCI_INTX(pin)), irq & 0xf);
	}
	printf("\n");

	{
		u8_t 	mbirq[2];
		int	i;
		char	*msg;

		printf("MBIRQ:\n");
		for(i=0;i<2;i++)
		{
			prcb(Pbn,Pdevfn,0x70+i,&mbirq[i]);
			if (mbirq[i] & 0x80)
				printf("[%d] disabled [%x]\n",i,mbirq[i]);
			else
			{
				msg=(mbirq[i] & 0x40)?"Shared" : "Not-Shared";
				printf("[%d] %s %d\n",i,msg,mbirq[i]&0xf);
			}
		}	
	}
	printf("\n");
}

void
show_pirq()
{
	int	pin;

	printf("PCI IRQ levels:\n");
	for(pin=1;pin<DEVPCI_LEGACY_IRQ_PINS+1;pin++)
	{
		printf(" PIRQ%c: ",IntPin(pin));
		if (pci_remaps[pin-1] & 0x80)
			printf("disabled\n");
		else
			printf("%d\n",pci_remaps[pin-1]);
	}
	printf("\n");
}

/*
 * The format of the ELCR is simple: It is a 16-bit bitmap where bit 0 controls
 * IRQ 0, bit 1 controls IRQ 1, etc.  If the bit is zero, the associated IRQ
 * is edge triggered. If the bit is one, the IRQ is level triggered.
 */
void
elcr_show()
{
	int	i;

	printf("ELCR Found. ISA IRQs programmed as (%04x):\n",elcr_status);
	for(i=0; i<16; i++) 
		printf(" %2d",i);
	printf("\n");

	for(i=0; i<16; i++) 
	{
		if (elcr_status & ELCR_MASK(i))
			printf("  L");
		else
			printf("  E");
	}
	printf("\n");
}

int
elcr_probe()
{
	elcr_status=inb(ELCR_PORT) | inb(ELCR_PORT+1) << 8;
	if ((elcr_status & (ELCR_MASK(0) | ELCR_MASK(1) | ELCR_MASK(2) |
			    ELCR_MASK(8) | ELCR_MASK(13))) != 0) {
		DrvDebug(_PCI,5,"elcr_probe(): Not Found\n");
		return ENXIO;
	}
	elcr_found=1;
	return 0;
}

enum intr_trigger
elcr_read_trigger(u32_t irq)
{
	if (elcr_status & ELCR_MASK(irq))
		return INTR_TRIGGER_LEVEL;
	else
		return INTR_TRIGGER_EDGE;
}

void
elcr_write_trigger(u32_t irq, enum intr_trigger trigger)
{
	int	new_status;

	if (trigger == INTR_TRIGGER_LEVEL)
		new_status = elcr_status | ELCR_MASK(irq);
	else
		new_status = elcr_status & ~ELCR_MASK(irq);

	if (new_status == elcr_status) return;

	elcr_status = new_status;
	if (irq >= 8)
		outb(ELCR_PORT+1, elcr_status>>8);
	else
		outb(ELCR_PORT, elcr_status & 0xff);
}

void
myset_elt(int irq, int mode)
{
	int i, port, bit;

	DrvDebug(_PCI,5,"myset_elt(%d,%d)\n",irq,mode);

	switch (irq) {
	case 0:
	case 1:
	case 2:
	case 13:
		mode = EDGE_TRIG;
		break;
	}
	if (irq > 7) {
		irq -= 8;
		port = ELCR_PORT1;
	} else
		port = ELCR_PORT0;

	bit = 1 << irq;

	i = inb(port);
	i &= ~bit;
	i |= (mode ? bit : 0);
	outb(port, i);

	if (port == ELCR_PORT0) {
		elcr_status = (elcr_status & 0xff00) | (i & 0x00ff);
	} else {
		elcr_status = (elcr_status & 0x00ff) | ((i & 0x00ff) << 8);
	}
	elcr_show();
		
	return;
}

#define IMASK(Pri,Pic)	iplmask[Pic+NPIC*Pri]

/*
 * Dynamically register an interrupt handler
 *
 * RegisterIRQ("ata",11, &ataintr, SPL6, INTR_TRIGGER_LEVEL);
 */
int
RegisterIRQ(char *name,int irq,int (*func)(),int pri,enum intr_trigger le)
{ 
	extern int	intnull(), (*ivect[])(), nintr;
	extern uchar_t	intpri[];
	int	old_intr_mask;

	DrvDebug(_PCI,5,"RegisterIRQ(%s,%08x,pri=%d)\n",name,func,pri);

	if (ivect[irq] == intnull) {
		ivect[irq]=func;
		intpri[irq]=pri;
		if ((int)(irq+1) > nintr)
			nintr=irq+1;
		if (splvalid_flag) {
			asm("cli");
			pic_add_handler(); /*irq*/
			asm("sti");
		}
	}
	else
	if (ivect[irq] == func)
		/*printf("Warning: IRQ %d already installed\n",irq);*/ ;
	else
		printf("Error: IRQ %d has handler %08x - check config\n",
			irq,ivect[irq]);

	old_intr_mask=level_intr_mask;
	switch(le) {
	case INTR_TRIGGER_EDGE:
		/*printf("Setting IRQ%d to EDGE\n",irq);*/
		level_intr_mask &= ~ELCR_MASK(irq);
		break;
	case INTR_TRIGGER_LEVEL:
		/*printf("Setting IRQ%d to Level\n",irq);*/
		level_intr_mask |= ELCR_MASK(irq);
		break;
	}
	if (old_intr_mask != level_intr_mask)
		elcr_write_trigger(irq, le); 

	return 0;
}
