/*
 * pci.c
 */
#include <stdarg.h>
#include <sys/types.h>
#include <sys/seg.h>
#include <sys/errno.h>
#include <sys/immu.h>
#include <sys/param.h>
#include <sys/kmem.h>
#include <sys/eisa.h>
#include <sys/ipl.h>
#include <sys/pic.h>
#include <sys/user.h>
#include <sys/uio.h>

#include "pci.h"
#include "pci_ids.h"
#include "pci_funcs.h"

extern int pci_debug;
extern int level_intr_mask;

u8_t	pci_remaps[4] = { 0 };
u8_t 	Pbn, Pdevfn;
pci_router_ops_t	*pci_router = 0;

struct resource_region {
	u32_t	base;
	u32_t	size;
	u32_t	type;
	char	*name;	
	caddr_t	addr;
};

#define MAX_RR	128
struct resource_region _RR[MAX_RR];

pcibus_t 	pci_root;
pcidev_t 	*pci_devices = 0;

/* Programmable Interrupt Controllers */

/* defined in conf.c, which is generated by config: */
extern  int     (*ivect[])();           /* interrupt routines */
extern  unsigned char intpri[];         /* priority levels for interrupts */
extern  int     nintr;                  /* number of interrupts */

extern  unsigned short imrport[];       /* intr mask port addrs for pics */
extern  unsigned char masterline[];     /* line this pic connected to */
extern  unsigned char curmask[];        /* current masks for pics */
extern  int     npic;                   /* number of pics configured */
extern 	int picmax;               /* index of last pic */

/*
 * iplmask[] contains the pic masks for each interrupt priority level.
 * It is effectively dimensioned iplmask[IPLHI][NPIC],
 * and is initialized from intpri[].
 * IPLHI=8 NPIC=2
 */
extern  unsigned char iplmask[];

extern  int     intnull();              /* null interrupt routine */
extern	int	splvalid_flag;

extern int ipl;                  /* current interrupt priority level */
extern int picipl;               /* interrupt priority level of pic masks */


/*
 * Main SVR4 Driver Entry points
 */
void
pciinit()
{
	uint_t	tmp;
	int	x;
	extern int verbose_bios;

	DrvDebug(_PCI,5,"pciinit()\n");
	if (pci_debug>0)
		verbose_bios=1;

	if (pci_devices != 0) return;

	outl(CFG_ADDR,0x80000000);
	tmp=inl(CFG_ADDR);
	if (tmp != 0x80000000)
	{
		printf("No PCI devices found\n");
		return;
	}

	pci_router=&pci_generic_router_ops;
	scan_bios();

	bzero(&pci_root, sizeof(pci_root));
	pci_root.subordinate = scan_bus(&pci_root);

	pci_devices = reverse_dev_list(pci_devices);
	reverse_bus_devices(&pci_root);

	if (elcr_probe() != 0)
		printf("PCI: ELCR not found, level-triggered IRQs not available\n");

	/* Probe chipset routers */
	(void)pci_probe_chipsets();

	/*
	 * Seed PIRQ interrupt weights now that scan_bus() has populated
	 * pci_devices with BIOS-assigned IRQs
	 */
	if (pci_route_table != NULL)
		pci_pir_init_weights();

	return; 
}

int
pciopen()
{
	DrvDebug(_PCI,5,"pciopen()\n");
	
	return 0;
}

int
pciclose()
{
	DrvDebug(_PCI,5,"pciclose()\n");

	return 0;
}

int
pciread(dev_t dev, uio_t *uio_p, cred_t *cred_p)
{
	static char buf[8192];
	off_t off;
	int len;

	DrvDebug(_PCI,5,"pciread()\n");

	if (uio_p == 0)
		return EINVAL;

	len = pci_format_snapshot(buf, sizeof(buf));
	if (len < 0)
		len = 0;

	off = uio_p->uio_offset;
	if (off < 0)
		off = 0;

	if (off >= len)
		return 0;	/* EOF */

	while (uio_p->uio_resid && off < len) {
		if (ureadc(buf[off], uio_p))
			return EFAULT;
		off++;
	}

	/*
	 * UnixWare/SVR4 new-style character drivers still require the
	 * legacy user structure to be reconciled after ureadc() loops.
	 */
	u.u_offset += u.u_count;
	u.u_count = 0;

	return 0;
}

int
pciwrite(dev_t dev, uio_t *uio_p, cred_t *cred_p)
{
	DrvDebug(_PCI,5,"pciwrite()\n");
	return ENODEV;
}
		
void
pci_buf_printf(char *buf, int maxlen, int *len, const char *fmt, ...)
{
	va_list ap;
	char tmp[256];
	int n;
	char *p;

	if (*len >= maxlen - 1)
		return;

	va_start(ap, fmt);
	kv_vsprintf(tmp, fmt, ap);
	va_end(ap);

	n = strlen(tmp);
	if (n <= 0)
		return;

	if (*len + n >= maxlen)
		n = (maxlen - 1) - *len;

	for (p = tmp; n-- > 0; p++)
		buf[(*len)++] = *p;

	buf[*len] = 0;
}

char
pci_intpin_name(u8_t pin)
{
	switch (pin) {
	case 1: return 'A';
	case 2: return 'B';
	case 3: return 'C';
	case 4: return 'D';
	}
	return '-';
}

char *
pci_display_name(pcidev_t *dev)
{
	u8_t base, sub;
	char *name;

#if 0
	if (dev->name != 0 && *dev->name != 0)
		return dev->name;
#endif

	base = (u8_t)((dev->class >> 16) & 0xff);
	sub  = (u8_t)((dev->class >> 8) & 0xff);

	name = get_pci_subclass_name(base, sub);
	if (name != 0)
		return name;

	name = get_pci_class_name(base);
	if (name != 0)
		return name;

	return "Unknown PCI Device";
}

void
pci_format_one_bar(resource_t *r, int barno, char *buf, int maxlen, int *len, int indent)
{
	char info[64];

	info[0] = 0;
	if (r->flags & IORESOURCE_IO) {
		strcpy(info, "IO ");
	} else if (r->flags & IORESOURCE_MEM) {
		strcpy(info, "MEM");
		if (r->flags & IORESOURCE_PREFETCH)
			strcat(info, " prefetch");
		if (r->flags & IORESOURCE_MEM_64)
			strcat(info, " 64-bit");
		else
			strcat(info, " 32-bit");
	} else {
		strcpy(info, "???");
	}

	pci_buf_printf(buf, maxlen, len,
	    "%*sBAR%d %-18s %08lx-%08lx\n",
	    indent, "",
	    barno,
	    info,
	    (unsigned long)r->start,
	    (unsigned long)r->end);
}

void
pci_format_bars(pcidev_t *dev, char *buf, int maxlen, int *len, int indent)
{
	int i;
	resource_t *r;

	for (i = 0; i < DEVICE_COUNT_RESOURCE; i++) {
		r = &dev->resource[i];
		if (r->flags == 0)
			continue;

		pci_format_one_bar(r, i, buf, maxlen, len, indent);
	}
}

void
pci_format_bus_tree(pcibus_t *bus, char *buf, int maxlen, int *len, int indent)
{
	pcidev_t *dev;

	for (dev = bus->devices; dev != 0; dev = dev->sibling) {
		pci_buf_printf(buf, maxlen, len,
		    "%*s%02x:%02x.%x %s [%04x:%04x] IRQ:%d INT#%c\n",
		    indent, "",
		    dev->bn,
		    PCI_SLOT(dev->devfn),
		    PCI_FUNC(dev->devfn),
		    pci_display_name(dev),
		    dev->vendor,
		    dev->device,
		    dev->irq,
		    pci_intpin_name(dev->intpin));

		pci_format_bars(dev, buf, maxlen, len, indent + 2);

		if (dev->child_bus != 0) {
			pci_buf_printf(buf, maxlen, len,
				"%*sBus %02x\n",
				indent+2,"",
				dev->child_bus->number);

			pci_format_bus_tree(dev->child_bus, buf, maxlen, len, indent + 2);
		}
	}
}

int
pci_format_snapshot(char *buf, int maxlen)
{
	int len = 0;
	int irq;

	if (maxlen <= 0)
		return 0;

	buf[0] = 0;
	pci_buf_printf(buf, maxlen, &len, "PCI device tree:\n");

	if (pci_router != 0) {
		pci_buf_printf(buf, maxlen, &len,
		    "Router: %s bus=%02x devfn=%02x base=0x%x\n",
		    pci_router->name ? pci_router->name : "(unknown)",
		    Pbn, Pdevfn, pci_router->pirq_base);

		if (pci_router->route != 0) {
			irq = pci_router->route(PIRQ_GET, 1);
			if (irq & 0x80)
				pci_buf_printf(buf, maxlen, &len, 
						"   PIRQA=disabled");
			else
				pci_buf_printf(buf, maxlen, &len, 
						"   PIRQA=%d", irq & 0x0f);
			irq = pci_router->route(PIRQ_GET, 2);
			if (irq & 0x80)
				pci_buf_printf(buf, maxlen, &len, 
						"   PIRQB=disabled");
			else
				pci_buf_printf(buf, maxlen, &len, 
						"   PIRQB=%d", irq & 0x0f);
			irq = pci_router->route(PIRQ_GET, 3);
			if (irq & 0x80)
				pci_buf_printf(buf, maxlen, &len, 
						"   PIRQC=disabled");
			else
				pci_buf_printf(buf, maxlen, &len, 
						"   PIRQC=%d", irq & 0x0f);
			irq = pci_router->route(PIRQ_GET, 4);
			if (irq & 0x80)
				pci_buf_printf(buf, maxlen, &len, 
						"   PIRQD=disabled\n");
			else
				pci_buf_printf(buf, maxlen, &len, 
						"   PIRQD=%d\n", irq & 0x0f);
		}
	}

	pci_format_bus_tree(&pci_root, buf, maxlen, &len, 2);

	if (len >= maxlen)
		len = maxlen - 1;
	buf[len] = 0;
	return len;
}


int
pci(int mode,u8_t bus,u8_t devfn,u8_t reg,u32_t value,int sz)
{
	u32_t	addr;
	u32_t	val;
	int	n;

	if (sz != 1 && sz != 2 && sz != 4) return -1;

	n=((int)reg%sizeof(u32_t))<<3;
	reg &= ~(sizeof(u32_t)-1);
			
	addr = PCI_ADDR(bus,devfn)|reg;
	outl(CFG_ADDR,addr);

	switch(mode) {
	case PCI_RD:
		if (value == 0) return -1;
		val=inl(CFG_DATA);
		switch(sz) {
		case 1:
			*(u8_t *)(ptrsize_t)value=(u8_t)((val>>n)&0xff);
			break;
		case 2:
			*(u16_t *)(ptrsize_t)value=(u16_t)((val>>n)&0xffff);
			break;
		case 4:
			*(u32_t *)(ptrsize_t)value=val;
			break;
		}
		break;

	case PCI_WR:
		val=inl(CFG_DATA);
		switch(sz) {
		case 1:
			val &= ~(0x000000ffU<<n);
			val |= (value & 0x000000ffU)<<n;
			break;
		case 2:
			val &= ~(0x0000ffffU<<n);
			val |= (value & 0x0000ffffU)<<n;
			break;
		case 4:
			val = value;
			break;
		}
		outl(CFG_ADDR,addr);
		outl(CFG_DATA,val);
		break;
	default:
		return -1;
	}
	return 0;
}

int
pci_ffs(int mask)
{
	int 	bit;

	if (mask==0) return 0;
	for(bit=1;!(mask&1); bit++)
		mask=(uint_t)mask>>1;
	return bit;
}

char 
IntPin(u8_t pin)
{
	switch(pin)
	{
	case 0: return '-';
	case 1: return 'A';
	case 2: return 'B';
	case 3: return 'C';
	case 4: return 'D';
	default: return '?';
	}
}


u32_t
barsize(u32_t mask)
{
	if (mask == 0) 
		return 0;
	return mask & (~mask + 1);
}

void
burst_bridge(u8_t bus, u8_t devfn, u8_t pos, int turn_on)
{
	DrvDebug(_PCI,5,"burst_bridge()\n");
}

void *
pci_malloc(int size)
{
	void	*mem=kmem_zalloc(size,KM_NOSLEEP);
	return mem;
}

int
get_num_bars(u8_t hdrtype)
{
	switch(hdrtype & 0x7f) {
	case 0: return 6;
	case 1: return 2;
	case 2: return 1;
	}
	return 0;
}

u32_t
get_map_base(u32_t addr) 
{
	if  (addr & 0x01)
		return addr & ~0x03;
	else
		return addr & ~0x0f;
}

void
pci_print_one_device(pcidev_t *dev)
{
	int	i;
	u8_t	base, sub, prog;
	char	*vendor_name;
	char	*device_name;
	char	*class_name;
	char	*subclass_name;

	DrvDebug(_PCI,5,"pci_print_one_device()\n");

	base = (u8_t)((dev->class >> 16) & 0xff);
	sub  = (u8_t)((dev->class >> 8) & 0xff);
	prog = (u8_t)(dev->class & 0xff);

	vendor_name = get_pci_vendor_name(dev->vendor);
	device_name = get_pci_dev(dev->vendor, dev->device);
	class_name = get_pci_class_name(base);
	subclass_name = get_pci_subclass_name(base, sub);

	printf("PCI: %02x:%02x.%x ",
		dev->bn,
		PCI_SLOT(dev->devfn),
		PCI_FUNC(dev->devfn));

	if (device_name != 0)
		printf("%s", device_name);
	else if (subclass_name != 0)
		printf("%s", subclass_name);
	else if (class_name != 0)
		printf("%s", class_name);
	else
		printf("Unknown PCI Device");

	printf(" [%04x:%04x]", dev->vendor, dev->device);
	if (vendor_name != 0)
		printf(" (%s)", vendor_name);
	printf(" class=%02x/%02x/%02x", base, sub, prog);
	if (dev->intpin != 0 || dev->irq != PCI_INVALID_IRQ)
		printf(" IRQ:%d INT#%c", dev->irq, IntPin(dev->intpin));
	printf("\n");

	for (i = 0; i < DEVICE_COUNT_RESOURCE; i++) {
		if (dev->resource[i].flags == 0)
			continue;

		printf("  BAR%d ", i);
		if (dev->resource[i].flags & IORESOURCE_IO)
			printf("IO  %08lx-%08lx",
				(unsigned long)dev->resource[i].start,
				(unsigned long)dev->resource[i].end);
		else if (dev->resource[i].flags & IORESOURCE_MEM)
			printf("MEM %08lx-%08lx",
				(unsigned long)dev->resource[i].start,
				(unsigned long)dev->resource[i].end);
		else
			printf("??? %08lx-%08lx",
				(unsigned long)dev->resource[i].start,
				(unsigned long)dev->resource[i].end);

		printf("\n");
	}
}

void
pci_print_devices(void)
{
	pcidev_t *dev;

	DrvDebug(_PCI,5,"pci_print_devices()\n");

	if (pci_devices == 0) {
		printf("PCI: no devices enumerated\n");
		return;
	}

	printf("PCI: enumerated devices\n");
	for (dev = pci_devices; dev != 0; dev = dev->next)
		pci_print_one_device(dev);
	printf("\n");
}

pcidev_t *
reverse_dev_list(pcidev_t *head)
{
	pcidev_t *prev=0, *curr=head, *next;

	while (curr != 0) {
		next = curr->next;
		curr->next = prev;
		prev = curr;
		curr = next;
	}
	return prev;
}

void
reverse_bus_devices(pcibus_t *bus)
{
	pcidev_t *prev=0, *curr = bus->devices, *next;

	while (curr != 0) {
		next = curr->sibling;
		curr->sibling = prev;
		prev = curr;
		curr = next;
	}
	bus->devices = prev;

	for(curr = bus->devices; curr != 0; curr = curr->sibling)
		if (curr->child_bus != 0)
			reverse_bus_devices(curr->child_bus);
}

u32_t
scan_bus(pcibus_t *bus)
{
	pcidev_t	*dev;
	pcibus_t	*child;
	u32_t		l, iostart, iosize, buses;
	u16_t		cmd, tmp, vid, did, ssvid, ssdid, cr;
	u32_t		class;
	u8_t		bn, max, hdr, mf, rev;
	u8_t		master, irq, intpin;
	u8_t		devfn;
	int		i, slot, fn, num_bars, nfuncs;
	resource_t	res[DEVICE_COUNT_RESOURCE];

	DrvDebug(_PCI,5,"scan_bus()\n");

	max = bus->secondary;
	bn  = bus->number;

	for (slot = 0; slot < 32; slot++)
	{
		hdr = vid = did = 0;
		devfn = DEVFN(slot, 0);

		prcw(bn, devfn, PCI_VENDOR_ID, &vid);
		if (vid == 0xffff || vid == 0x0000)
			continue;

		/* Read header type from function 0 to determine
		 * whether this is a multi-function device. */
		prcb(bn, devfn, PCI_HEADER_TYPE, &hdr);
		if (hdr == 0xff)
			continue;		/* slot not populated */

		mf    = (hdr & 0x80) ? 1 : 0;
		hdr  &= ~0x80;
		nfuncs = mf ? 8 : 1;

		for (fn = 0; fn < nfuncs; fn++)
		{
			devfn = DEVFN(slot, fn);

			/* For fn > 0 re-read vendor to skip unpopulated
			 * functions in a multi-function device. */
			if (fn > 0) {
				vid = 0;
				prcw(bn, devfn, PCI_VENDOR_ID, &vid);
				if (vid == 0xffff || vid == 0x0000)
					continue;
			}

			prcw(bn, devfn, PCI_DEVICE_ID, &did);
			if (did == 0xffff)
				continue;

			/* Re-read header type for each function it can
			 * differ across functions of the same device. */
			if (fn > 0) {
				hdr = 0;
				prcb(bn, devfn, PCI_HEADER_TYPE, &hdr);
				if (hdr == 0xff)
					continue;
				hdr &= ~0x80;
			}

			num_bars = get_num_bars(hdr);

			/* Subsystem vendor is at 0x2c, subsystem ID at 0x2e.
			 * These registers are only valid for header type 0. */
			ssvid = 0;
			ssdid = 0;
			if ((hdr & 0x7f) == 0) {
				prcw(bn, devfn, PCI_SUBSYSTEM_VENDOR_ID, &ssvid);
				prcw(bn, devfn, PCI_SUBSYSTEM_ID,        &ssdid);
			}

			/* Class (24 bits) and revision (8 bits) share one
			 * DWORD at offset 0x08. */
			l   = 0;
			prcd(bn, devfn, PCI_CLASS_REVISION, &l);
			rev   = (u8_t)(l & 0xff);
			class = (l >> 8) & 0x00ffffffU;

			/* BAR probing: write all-ones, read back to determine
			 * size, then restore original value. */
			bzero(res, sizeof(res));
			for (i = 0; i < num_bars; i++)
			{
				u32_t bar_reg = PCI_BASE_ADDRESS_0 + (i * 4);
				u32_t size;

				iosize = 0;
				if (prcd(bn, devfn, bar_reg, &iostart) != 0)
					continue;

				if (iostart != 0 && iostart != 0xffffffff) {
					if (pwcd(bn,devfn,bar_reg,0xffffffff) != 0) continue;
					if (prcd(bn,devfn,bar_reg,&iosize) != 0) continue;
					if (pwcd(bn,devfn,bar_reg,iostart) != 0) continue;
				}

				if (iostart == 0 || iostart == 0xffffffff) {
					res[i].start = 0;
					res[i].end   = 0;
					res[i].flags = 0;
					continue;
				}

				res[i].start = get_map_base(iostart);
				if (iostart & PCI_BASE_ADDRESS_SPACE_IO) {
					size = barsize(iosize & PCI_BASE_ADDRESS_IO_MASK);
					res[i].flags = IORESOURCE_IO;
				} else {
					size = barsize(iosize & PCI_BASE_ADDRESS_MEM_MASK);
					res[i].flags = IORESOURCE_MEM;
				}
				res[i].end = size ? (res[i].start + size - 1) : 0;
			}

			/* Non-destructively test whether device supports
			 * bus mastering. */
			master = 0;
			if ((prcw(bn, devfn, PCI_COMMAND, &cmd) == 0) &&
			    (pwcw(bn, devfn, PCI_COMMAND, (cmd | PCI_COMMAND_MASTER)) == 0) &&
			    (prcw(bn, devfn, PCI_COMMAND, &tmp) == 0))
			{
				master = ((tmp & PCI_COMMAND_MASTER) != 0) ? 1 : 0;
				pwcw(bn, devfn, PCI_COMMAND, cmd);
			}

			/* Read IRQ line and interrupt pin.*/
			irq    = 0;
			intpin = 0;
			if (prcb(bn, devfn, PCI_INTERRUPT_LINE, &irq) != 0) continue;
			if (prcb(bn, devfn, PCI_INTERRUPT_PIN,  &intpin) != 0) continue;
			if (intpin > 4) intpin=0;

			/* Allocate device and info structures.
			 * Bug fixed: original allocated dev then immediately
			 * tested dev->info in the same if-condition, but if
			 * dev allocation succeeded and info allocation failed
			 * the already-allocated dev was leaked. Fix: allocate
			 * and test separately. */
			dev = pci_malloc(sizeof(pcidev_t));
			if (dev == 0)
				continue;

			dev->info = pci_malloc(sizeof(pcidevinfo_t));
			if (dev->info == 0) {
				kmem_free(dev, sizeof(pcidev_t));
				continue;
			}

			dev->bus              = bus;
			dev->bn               = bus->number;
			dev->devfn            = devfn;
			dev->vendor           = vid;
			dev->device           = did;
			dev->subsystem_vendor = ssvid;
			dev->subsystem_device = ssdid;
			dev->revision         = rev;
			dev->class            = class;
			dev->hdr_type         = hdr;
			dev->master           = master;
			dev->irq              = irq;
			dev->intpin           = intpin;
			bcopy(&res, &dev->resource, sizeof(res));

			dev->info->vendor = vid;
			dev->info->device = did;
			dev->info->name   = "Unknown PCI Device";
			dev->name         = 0;
			dev->child_bus    = 0;

			/* Prepend to global device list and bus device list. */
			dev->next    = pci_devices;
			pci_devices  = dev;
			dev->sibling = bus->devices;
			bus->devices = dev;

			/* If this is a PCI-to-PCI bridge, allocate a child
			 * bus structure, assign tentative bus numbers, recurse
			 * to scan subordinate buses, then write the final
			 * subordinate number back. */
			if ((dev->class>>8) == PCI_CLASS_BRIDGE_PCI)
			{
				child = kmem_zalloc(sizeof(pcibus_t), KM_NOSLEEP);
				if (child == 0)
					continue;

				child->self        = dev;
				child->parent      = bus;
				child->number      = ++max;
				child->secondary   = max;
				child->primary     = bus->number;
				child->subordinate = 0xff;

				child->next  = bus->children;
				bus->children = child;
				dev->child_bus = child;

				/* Disable the bridge while we configure it. */
				prcw(bn, devfn, PCI_COMMAND, &cr);
				pwcw(bn, devfn, PCI_COMMAND, 0x0000);
				pwcw(bn, devfn, PCI_STATUS,  0xffff);

				/* Write primary, secondary, subordinate bus
				 * numbers into the bridge's config space.
				 * Preserve the top byte (secondary latency). */
				prcd(bn, devfn, 0x18, &buses);
				buses &= 0xff000000U;
				buses |= ((u32_t)child->primary     <<  0)
				       | ((u32_t)child->secondary   <<  8)
				       | ((u32_t)child->subordinate << 16);
				pwcd(bn, devfn, 0x18, buses);

				/* Recurse — fills in child->subordinate. */
				max = scan_bus(child);

				/* Write the real subordinate number back. */
				child->subordinate = max;
				buses = (buses & 0xff00ffffU)
				      | ((u32_t)max << 16);
				pwcd(bn, devfn, 0x18, buses);

				/* Re-enable the bridge. */
				pwcw(bn, devfn, PCI_COMMAND, cr);
			}
		}
	}
	return max;
}

static pcidevid_t *
pci_match_one_device(pcidev_t *dev,pcidevid_t *id)
{
	if ((id->vendor == PCI_ANY_ID || id->vendor == dev->vendor) &&
	    (id->device == PCI_ANY_ID || id->device == dev->device) &&
	    (id->subvendor == PCI_ANY_ID || 
	     id->subvendor == dev->subsystem_vendor) &&
	    (id->subdevice == PCI_ANY_ID || 
	     id->subdevice == dev->subsystem_device) &&
	    !((id->class ^ dev->class) & id->class_mask))
		return id;
	return 0;
}

pcidev_t *
find_pcidev(u8_t bus,u8_t devfn)
{
	pcidev_t *dev;

	DrvDebug(_PCI,5,"find_pcidev()\n");

	/*** For each pci_devices */
	for(dev=pci_devices; dev; dev=dev->next)
	{
		/* printf("dev %02x.%02x.%x [%04x,%04x]\n",
			dev->bn,dev->devfn,
			dev->vendor,dev->device);*/
		if (dev->bn == bus &&
		    dev->devfn == devfn)
			return dev; 
	}
	return (pcidev_t *)0;
}

/*
 * called with (struct pci_driver *)&pcnet_driver
 */
int
pci_register_driver(struct pci_driver *drv)
{
	pcidev_t *dev;
	pcidevid_t *id;
	int	count=0;

	DrvDebug(_PCI,5,"pci_register_driver(%s)\n",drv ? drv->name : "??");

	if (!drv || !drv->id_table)
		return -EINVAL;

	/*** For each pci_devices */
	for(dev=pci_devices; dev; dev=dev->next)
	{
		/*
		printf("dev %x %02x.%02x.%x [%04x,%04x]\n",
			dev,
			dev->bn,PCI_SLOT(dev->devfn),PCI_FUNC(dev->devfn),
			dev->vendor,dev->device); */

		for(id=drv->id_table; id->vendor; id++)
		{
			if (pci_match_one_device(dev,id) != 0) {
				int ret=0;

				if (drv->probe)
					ret = (*drv->probe)(dev,id);

				if (ret == 0) {
					dev->name = drv->name;
					dev->info->name = drv->name;
					count++;
					break;
				}
			}
		}
	}
	return count;
}

uint_t	pcibios_max_latency = 255;

int
pci_is_enabled(pcidev_t *dev)
{
	return dev->enable_cnt > 0;
}

void
pci_set_master(pcidev_t *dev)
{
	u16_t	cmd;
	u8_t	lat=0;

	DrvDebug(_PCI,5,"pci_set_master()\n");

	if (dev == 0)
		return;

	if (prcw(dev->bn, dev->devfn, PCI_COMMAND, &cmd) != 0)
		return;

	if (!(cmd & PCI_COMMAND_MASTER)) {
		cmd |= PCI_COMMAND_MASTER;
		if (pwcw(dev->bn, dev->devfn, PCI_COMMAND, cmd) != 0)
			return;
	}

	dev->is_busmaster = 1;

	if (prcb(dev->bn,dev->devfn,PCI_LATENCY_TIMER,&lat) == 0) {
		if (lat < 16) {
			lat=64;	
			pwcb(dev->bn,dev->devfn,PCI_LATENCY_TIMER,lat);
		}
	}
	return;
}

pcidev_t *
pci_physfn(pcidev_t *dev)
{
	/* if (dev->is_virtfn)
		dev=dev->physfn;*/
	return dev;
}

pcidev_t *
pci_upstream_bridge(pcidev_t *dev)
{
	dev=pci_physfn(dev);
	if (pci_is_root_bus(dev->bus))
		return NULL;
	return dev->bus->self;
}

void
pci_enable_bridge(pcidev_t *dev)
{
	pcidev_t *bridge;
	int	retval;

	DrvDebug(_PCI,5,"pci_enable_bridge()\n");

	bridge=pci_upstream_bridge(dev);
	if (bridge)
		pci_enable_bridge(bridge);
	if (pci_is_enabled(dev)) {
		if (!dev->is_busmaster)
			pci_set_master(dev);
		return;
	}
	retval=pci_device_enable(dev);
	if (retval)
		printf("Error enabling device %02d:%02d.%d\n",
			dev->bn,
			PCI_SLOT(dev->devfn),
			PCI_FUNC(dev->devfn));
	pci_set_master(dev);
}

int
pci_is_root_bus(pcibus_t *bus)
{
	return !(bus->parent);
}

int
pci_is_bridge(pcidev_t *dev)
{
	return dev->hdr_type == PCI_HEADER_TYPE_BRIDGE ||
	       dev->hdr_type == PCI_HEADER_TYPE_CARDBUS;
}

int
do_pci_device_enable(pcidev_t *dev,int bars)
{
	u16_t	cmd, newcmd;
	int	i;

	DrvDebug(_PCI,5,"do_pci_device_enable()\n");

	if (dev == 0)
		return -EINVAL;

	if (prcw(dev->bn, dev->devfn, PCI_COMMAND, &cmd) != 0)
		return -EIO;

	newcmd = cmd;

	for (i = 0; i < PCI_ROM_RESOURCE; i++) {
		if (!(bars & (1 << i)))
			continue;
		if (dev->resource[i].flags & IORESOURCE_IO)
			newcmd |= PCI_COMMAND_IO;
		if (dev->resource[i].flags & IORESOURCE_MEM)
			newcmd |= PCI_COMMAND_MEMORY;
	}

	if (dev->master)
		newcmd |= PCI_COMMAND_MASTER;

	if (newcmd == cmd) {
		if (newcmd & PCI_COMMAND_MASTER)
			dev->is_busmaster = 1;
		return 0;
	}

	if (pwcw(dev->bn, dev->devfn, PCI_COMMAND, newcmd) != 0)
		return -EIO;

	if (newcmd & PCI_COMMAND_MASTER)
		dev->is_busmaster = 1;

	return 0;
}

int
pci_device_disable(pcidev_t *dev)
{
	u16_t	cmd;

	DrvDebug(_PCI,5,"pci_device_disable()\n");

	if (dev == 0)
		return -EINVAL;

	if (dev->enable_cnt <= 0) {
		dev->enable_cnt = 0;
		return 0;
	}

	dev->enable_cnt--;
	if (dev->enable_cnt > 0)
		return 0;

	if (prcw(dev->bn, dev->devfn, PCI_COMMAND, &cmd) != 0)
		return -EIO;

	cmd &= ~(PCI_COMMAND_IO | PCI_COMMAND_MEMORY | PCI_COMMAND_MASTER);

	if (pwcw(dev->bn, dev->devfn, PCI_COMMAND, cmd) != 0)
		return -EIO;

	dev->is_busmaster = 0;
	return 0;
}

int
pci_device_enable_flags(pcidev_t *dev,u32_t flags)
{
	pcidev_t *bridge;
	int	err, i, bars=0;

	DrvDebug(_PCI,5,"pci_device_enable_flags()\n");

	if (dev->pm_cap) {
		u16_t 	pmcsr;

		if (prcw(dev->bus->number,
			      dev->devfn,
			      dev->pm_cap+PCI_PM_CTRL,
			      &pmcsr) == 0)
			dev->current_state=(pmcsr & PCI_PM_CTRL_STATE_MASK);
	}
	if (dev->enable_cnt > 0) {
		dev->enable_cnt++;
		return 0;
	}

	dev->enable_cnt++;

	bridge=pci_upstream_bridge(dev);
	if (bridge)
		pci_enable_bridge(bridge);

	for (i=0;i<PCI_ROM_RESOURCE;i++)
		if (dev->resource[i].flags & flags)
			bars |= (1 << i);

	err=do_pci_device_enable(dev,bars);
	if (err<0)
		dev->enable_cnt=0;
	return err;
}

int
pci_device_enable(pcidev_t *dev)
{
	return pci_device_enable_flags(dev,IORESOURCE_MEM|IORESOURCE_IO);
}

int
pci_set_dma_mask(pcidev_t *dev,u32_t mask)
{
	dev->dma_mask = mask;
	return 0;
}

int
rr_overlap(u32_t base1, u32_t size1, u32_t base2, u32_t size2)
{
	u32_t end1, end2;

	if (size1 == 0 || size2 == 0)
		return 0;

	end1 = base1 + size1;
	end2 = base2 + size2;

	if (end1 <= base1 || end2 <= base2)
		return 0;

	return (base1 < end2 && end1 > base2);
}

int
request_region(u32_t type, u32_t base, u32_t size, char *name)
{
	int	i, free_slot;
	caddr_t	addr;
	u32_t	end;

	DrvDebug(_PCI,5,"request_region(%d,%x,%x,%s)\n",
		type, base, size, name ? name : "(null)");

	if (type != RES_MEM && type != RES_IO)
		return 0;

	if (size == 0)
		return 0;

	end = base + size;
	if (end <= base)
		return 0;

	free_slot = -1;

	for (i = 0; i < MAX_RR; i++) {
		if (_RR[i].size == 0) {
			if (free_slot < 0)
				free_slot = i;
			continue;
		}

		if (_RR[i].type != type)
			continue;

		if (rr_overlap(base, size, _RR[i].base, _RR[i].size)) {
			DrvDebug(_PCI,5,
			    "request_region: overlap [%x..%x) with [%x..%x) %s\n",
			    base, base + size,
			    _RR[i].base, _RR[i].base + _RR[i].size,
			    _RR[i].name ? _RR[i].name : "(unnamed)");
			return 0;
		}
	}

	if (free_slot < 0) {
		printf("MAX Resources RR reached for PCI\n");
		return 0;
	}

	addr = 0;
	if (type == RES_MEM) {
		addr = (caddr_t)physmap(base, size, KM_NOSLEEP);
		if (addr == 0)
			return 0;
	}

	_RR[free_slot].base = base;
	_RR[free_slot].size = size;
	_RR[free_slot].type = type;
	_RR[free_slot].name = name;
	_RR[free_slot].addr = addr;

	return 1;
}

int
release_region(u32_t type, u32_t base, u32_t size)
{
	int	i;

	DrvDebug(_PCI,5,"release_region(%d,%x,%x)\n", type, base, size);

	for (i = 0; i < MAX_RR; i++) {
		if (_RR[i].size == 0)
			continue;

		if (_RR[i].type != type)
			continue;

		if (_RR[i].base == base && _RR[i].size == size) {
			if (type == RES_MEM && _RR[i].addr != 0)
				physmap_free(_RR[i].addr, _RR[i].size, KM_NOSLEEP);

			_RR[i].base = 0;
			_RR[i].size = 0;
			_RR[i].type = RES_NONE;
			_RR[i].name = 0;
			_RR[i].addr = 0;
			return 1;
		}
	}

	return 0;
}

/*
 * pic_add_handler() - update PIC masks after adding a new IRQ handler
 * must be called at spl7() with interrupts disabled
 */
void
pic_add_handler()
{
	int 	mask,intno, bit, slaves, level, pic;

	DrvDebug(_PCI,9,"pic_add_handler()\n");

	/*
	 * if picinit() has not yet run skip the hw update
	 * picinit() will pick this up when it runs
	 */
	if (!splvalid_flag)
		return;

	for (pic=0; pic<npic; pic++) {
		mask=0;
		intno = pic * 8;
		for(bit=1; bit<=0x80; bit<<=1, intno++) {
			if (intno >= nintr || ivect[intno] == intnull) {
				mask |= bit;
				for(level=SPLTTY; level<IPLHI; level++)
					iplmask[level * npic+pic] |= bit;
			} else {
				level = intpri[intno];
				for(; level<IPLHI; level++)
					iplmask[level * npic+pic] |= bit;
			}
		}
		iplmask[0 * npic+pic]=mask;
	}

	/* Re-enable slave cascade lines on master */
	slaves = 0;	
	for(pic=1; pic<npic; pic++)
		slaves |= 1 << masterline[pic];
	iplmask[0] &= ~slaves;

	/* Write new OCW1 masks only - no ICW sequence */
	for(pic=0; pic<npic; pic++)
		outb(imrport[pic], (curmask[pic] = iplmask[pic]));
}

/*
 * Dynamically register an interrupt handler
 *
 * RegisterIRQ("ata",11, &ataintr, SPL6, INTR_TRIGGER_LEVEL);
 */
int
RegisterIRQ(char *name,int irq,int (*func)(),int pri,enum intr_trigger le)
{ 
	extern int	intnull(), (*ivect[])(), nintr;
	extern uchar_t	intpri[];
	int	old_intr_mask;

	DrvDebug(_PCI,5,"RegisterIRQ(%s,%08x,pri=%d)\n",name,func,pri);

	if (irq < 0 || irq >= NUM_ISA_INTERRUPTS) {
		printf("RegisterIRQ: IRQ %d out of range\n",irq);
		return -1;
	}

	if (ivect[irq] == intnull) {
		ivect[irq]=func;
		intpri[irq]=pri;
		if ((int)(irq+1) > nintr)
			nintr=irq+1;
		if (splvalid_flag) {
			int s=spl7();
			pic_add_handler(); /*irq*/
			splx(s);
		}
	}
	else
	if (ivect[irq] == func)
		/*printf("Warning: IRQ %d already installed\n",irq);*/ ;
	else
		printf("Error: IRQ %d has handler %08x - check config\n",
			irq,ivect[irq]);

	old_intr_mask=level_intr_mask;
	switch(le) {
	case INTR_TRIGGER_EDGE:
		/*printf("Setting IRQ%d to EDGE\n",irq);*/
		level_intr_mask &= ~ELCR_MASK(irq);
		break;
	case INTR_TRIGGER_LEVEL:
		/*printf("Setting IRQ%d to Level\n",irq);*/
		level_intr_mask |= ELCR_MASK(irq);
		break;
	}
	if (old_intr_mask != level_intr_mask)
		elcr_write_trigger(irq, le); 

	return 0;
}

int
request_mem_region(u32_t base, u32_t size, char *name)
{
	return request_region(RES_MEM, base, size, name);
}

int
release_mem_region(u32_t base, u32_t size)
{
	return release_region(RES_MEM, base, size);
}

int
request_io_region(u32_t base, u32_t size, char *name)
{
	return request_region(RES_IO, base, size, name);
}

int
release_io_region(u32_t base, u32_t size)
{
	return release_region(RES_IO, base, size);
}
